### ISSUE TITLE
InetSource does not work

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.inet#100]
I edited the GetWeather.spl testcase:

composite GetWeather
{
  graph
    stream<list<rstring> result> Result = InetSource()
    {
      //param URIList : ["http://www.weather.gov/alerts-beta/us.atom"];
      param URIList : ["https://github.com/IBMStreams/streamsx.inet"
      /*"http://weather.noaa.gov/pub/data/observations/metar/cycles/00Z.TXT",
                       "http://weather.noaa.gov/pub/data/observations/metar/cycles/01Z.TXT",
                       "http://weather.noaa.gov/pub/data/observations/metar/cycles/02Z.TXT"*/];
            incrementalFetch : true;
//            inputLinesPerRecord : 3u;
//            fetchInterval : 60.0;
            emitTuplePerURI : true;
    } 

    () as Writer = Custom(Result)
    {
      logic
        onTuple Result:
        {
          printStringLn("Some result!!!!!!!!!!\n");
          printStringLn("result: " + result[0] + "\n");
          flushStdio();
        } 
    }
}

This is the output I got from it:
Some result!!!!!!!!!!

result:

**Comment by hildrum** [comment]
In a design decision that goes back to Streams 2.0 (ie, not mine), InetSource's output is a list of strings, where each string represents one line of the result of the http request.  If you do a wget on your chosen URL, you'll see that the first few lines are blank:
```



<!DOCTYPE html>
<html lang="en" class="">
  <head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# object: http://ogp.me/ns/object# article: http://ogp.me/ns/article# 
profile: http://ogp.me/ns/profile#">
```
and in the Writer, you're only printing the first line, which is a blank.  I changed it to print the 10th line, and I got:
```result:     <meta name="msapplication-TileImage" content="/windows-tile.png">     <meta name="msapplication-TileColor" content="#ffffff">```

**Comment by chanskw** [comment]
If that is the case, then the InetSample needs to be updated as the sample provides no output.
I tried the original links.. and got no output either.

**Comment by hildrum** [comment]
The sample & several variations I have on it work for me.  I also tried getting rid of ` inputLinesPerRecord : 3u;` and `fetchInterval` and the sample still worked for me.

Is it possible you're experiencing firewall problems?  What happens if you do 
`wget http://weather.noaa.gov/pub/data/observations/metar/cycles/00Z.TXT`

**Comment by chanskw** [comment]
I get this:

--2015-02-05 22:23:37--  http://weather.noaa.gov/pub/data/observations/metar/cycles/00Z.TXT
Resolving weather.noaa.gov... 96.17.10.57, 96.17.10.73
Connecting to weather.noaa.gov|96.17.10.57|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1670672 (1.6M) [text/plain]
Saving to: “00Z.TXT”

100%[======================================>] 1,670,672   2.36M/s   in 0.7s    

2015-02-05 22:23:38 (2.36 MB/s) - “00Z.TXT” saved [1670672/1670672]

**Comment by chanskw** [comment]
Are you running the latest Streams 3.2.2? or Streams 3.2.1?

**Comment by chanskw** [comment]
... and launching it again works this time!  very strange.  
I have been trying this all day and it did not work.

**Comment by chanskw** [comment]
Closing... not sure why it is working now.
