### ISSUE TITLE
Doc clarification for tuple viewer

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.inet#101]
In the spl doc at http://ibmstreams.github.io/streamsx.inet/com.ibm.streamsx.inet/doc/spldoc/html/com.ibm.streamsx.inet.rest$HTTPTupleView.html

It mentions a /json url, but I don't find this particular url anywhere and not sure if it still exis

**Comment by ddebrunner** [comment]
Do you mean the /json URl doesn't work?


It's described in the source (and thus should be in the SPLDOC) at line 43 onwards of TupleView.java.

**Comment by conglisc** [comment]
I think it should be /tuples rather than /json.
