### ISSUE TITLE
Makefile for samples need to work in both product and open-source

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.inet#103]
The Makefiles in $STREAMS_INSTALL/samples/com.ibm.streamsx.inet/HTTPStreamRead as well as the InetSource and InetSourceDynamicURL samples all use this definition to specify the location of the toolkit:

STREAMS_INET_TOOLKIT ?=../../com.ibm.streamsx.inet

However, the relative path to the toolkit from those directories is actually this:
../../../toolkits/com.ibm.streamsx.inet

So, "make" fails with the toolkit not being found.

toolkit path should be set to:
STREAMS_INET_TOOLKIT ?=../../com.ibm.streamsx.inet:${STREAMS_INSTALL}/toolkits/com.ibm.streamsx.inet

**Comment by chanskw** [comment]
Marking as must-fix for now so we can find this.

**Comment by chanskw** [comment]
Moved as a streams322_candidate... to fix at next possible chance.

**Comment by hildrum** [comment]
I pushed a fix to the toolkitlocation branch.  Let me know when you want to pull it in.

**Comment by conglisc** [comment]
Hi chankskw,

I made changes to all samples' MakeFile to include inet toolkit location at ${STREAMS_INSTALL}/toolkits/com.ibm.streamsx.inet. A pull request has been made.

**Comment by hildrum** [comment]
That doesn't work for people who import the projects into Eclipse.

**Comment by conglisc** [comment]
I think this issue is more about command line scenario, i.e build samples via MakeFile.

If anyone wants to load the Inet project and samples into Eclipse via Egit, The project/sample code do not get copied to Eclipse workspace, it should still point to the git clone directory, thus makeFile will build successfully.

**Comment by ddebrunner** [comment]
It also won't work for people using the open source version of the toolkit, rather than the one from the Streams product.

**Comment by hildrum** [comment]
@conglisc -- It was a problem I or someone I was working with ran into at some point.
@ddebrunner -- What's your suggested behavior?   What I figured made sense was to use  ../../com.ibm.streamsx.inet  if it existed, if not, to use  ../com.ibm.streamsx.inet existed, and if that also didn't exist, then it used $STREAMS_INSTALL/com.ibm.streamsx.inet.   That's the behavior in the toolkitlocation branch.

Also, this is the same issue as #65 so whenever this one is closed, #65 should be too.

**Comment by conglisc** [comment]
@ddebrunner @hildrum Other than the 2 identified ient toolkit path (../../com.ibm.streamsx.inet:${STREAMS_INSTALL}/toolkits/com.ibm.streamsx.inet), if the inet toolkit path is located in a different directory, then user can always overwrite the STREAMS_INET_TOOLKIT variable in the makeFile by following methods.

1. If running makeFile in command line mode, user can specify the Inet toolkit path like 
make STREAMS_INET_TOOLKIT=/path/to/Inet/toolkit
2. In the case of running the sample from studio via external builder, user can specify a environment variable in the Environment properties window via "Configure SPL Build" option, i.e STREAMS_INET_TOOLKIT | /path/to/Inet/toolkit

We will need to document the procedure/instructions in the MakeFile to clarify different options. This way, user can explicitly specify the toolkit path that they want to use for compiling and running the samples.

Please let me know your thoughts on this.

**Comment by joergboe** [comment]
see PR #340
