### ISSUE TITLE
Need clarification on HTTPGetStream and HTTPPost, and suggestions

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.inet#105]
The two operators have the following parameters:
- maxRetries = Maximum number of retries in case of failures/disconnects.

In other operators (e.g. MQTT), we support the following retry configurations:
0 - no retry
n - n number of retries
-1 - inifinite number of retries.

Is this similar?  what happens when user enter 0 / -1?
- retryDelay - Wait time between retries in case of failures/disconnects.

What unit is this retryDelay expressed in?  ms?  seconds?
- retryOnClose - Retry connecting if the connection has been closed. Default is false

This is similar to retry policies from operators in the product... to allow user to control whether retry should be done when connection is dropped.  However, the parameters for this operator are not set up to be consistent with other operators (e.g. MQTT, JMS).

The messaging operators are set up with the following parameters... and when we designed them, we made sure that they are consistent with other operators in the product:

period = retryDelay
maxRetries = reconnectionBound 
retryOnClose = reconnectionPolicy from JMS

For MQTT, which is also a Java operator, we opted to remove reconnectionPolicy because Java operator did not support custom literal.  And we combined the concept with reconnectionBound. 

reconnectionBound = 0 - no retry
reconnectionBound = n - n number of retries
reconnectonBound = -1 - infinite retries. 

For usability, we should try to make the design of the operators and parameters as consistent as possible.
- HTTPGetStream - this is a source operator, and with a source operator, should we add an initDelay parameter?

**Comment by joergboe** [comment]
These operator is deprecated
