### ISSUE TITLE
TupleViewer does not seem to work if operator is in a composite

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.inet#106]
I have this testcase.

I tried the following URLs to try to see the tuples being generated...

http://127.0.0.1:8080/MapData2/ports/input/0/info - This URL will always get back some data
http://127.0.0.1:8080/MapData/ports/input/0/info - This will also result in a not found error.

The only difference is that the second URL is related to the TupleViewer operator that is placed inside a composite.  If I move the operator to my main composite, then the second URL will work.

composite Main
{
	graph
		(stream<float64 latitude, float64 longitude> Custom_1_out0) as Custom_1 =
			Custom()
		{
			logic
				onProcess :
				{
					while(! isShutdown())
					{
						float64 latitude = randomLatitude() ;
						float64 longitude = randomLongitude() ;
						submit({ latitude = latitude, longitude = longitude }, Custom_1_out0) ;
						block(0.5) ;
					}

				}

		}

		() as MapViewer_2 = MapViewer(Custom_1_out0)
		{
		}

		() as MapData2 = HTTPTupleView(Custom_1_out0 as inPort0Alias)
		{
			window
				inPort0Alias : tumbling, count(1) ;
			config
				placement : partitionColocation("jetty") ;
		}

}

public composite MapViewer(input stream<float64 latitude, float64 longitude> In0 )
{
	graph
		() as MapData = HTTPTupleView(In0 as inPort0Alias)
		{
			window
				inPort0Alias : tumbling, count(1) ;
			config
				placement : partitionColocation("jetty") ;
		}

		() as Map = HTTPTupleView(In0 as inPort0Alias)
		{
			window
				inPort0Alias : tumbling, count(1) ;
			param
				contextResourceBase : getThisToolkitDir() + "/etc" ;
				context : "map" ;
			config
				placement : partitionColocation("jetty") ;
		}

}

**Comment by hildrum** [comment]
I'm a little confused by the formatting, but the MapData URL you gave above shouldn't work as I read the documentation.  For the first HTTPTupleView (without the context), the URL should be `http://127.0.0.1:8080/MapViewer_2.MapData/ports/input/0/info` (ie, you need the full operator name, since no context is specified) for the second HTTPTupleView, I'd think `http://127.0.0.1:8080/map/Map/ports/input/0/info` would be the URL (the URL contains `context/baseopname`).

**Comment by chanskw** [comment]
I will try again.  Perhaps a nice enhancement is to print out what we expect the URLs to be from the operator.  So we don't have to guess.  But I will check again.

**Comment by hildrum** [comment]
The sample has this to say, which might be helpful: 
````
* This fixed URL shows information for all ports available through URLs
* in the HTTP server [http://127.0.0.1:8080/ports/info]
````
I'm not sure when we'd print out expected URLs (In the logs?  To standard out?)  

In any case, it looks like there's a problem with the SPLDoc generated from the HTTPTupleView sample.  We might also consider adding an example.

**Comment by ddebrunner** [comment]
@chanskw I think the trace output does list the URLs being provided.

**Comment by chanskw** [comment]
Thanks.. I am closing for now.. I may have done something wrong...
