### ISSUE TITLE
Syntax error when specified user ID with @ on https on param URIList for InetSource operator using Internet Toolkit

### ISSUE THREAD

**Issue by spchang** [IBMStreams/streamsx.inet#108]
Customer try to access data source using https from a source require user ID and password. Id is test@tw.ibm.com and password test123!

the http protocol specify syntax as https://userID:passwd@system:port/Resource_location

So, https://test@tw.ibm.com:test123!@216.46.190.179:443/accounts/IBMGBS/publishers/twitter/streams/track/prod.json was specified but got following error during runtime

=============================================================================
"The Uniform Resource Identifier string https://test@tw.ibm.com:test123!@216.46.190.179:443/accounts/IBMGBS/publishers/twitter/streams/track/prod.json specified in the URIList parameter contains a syntax error.  The Processing Element will shut down now."
=============================================================================

Replace with https://test%40tw.ibm.com:test123!@216.46.190.179:443/accounts/IBMGBS/publishers/twitter/streams/track/prod.json

still fail. %40 is @ .

I am wondering if two @ cause confusion but don't remember what is the right escape character or there are other way to specify it on this environment.

**Comment by hildrum** [comment]
It looks as if the operator wasn't expecting an `@` as part of the user name.  So, if you can use a username without an `@`, you can use the toolkit as-is.

As an alternative, I created a branch_108, I added a change that allows a `@` in the username.  You can try that out and let me know if it works.

**Comment by spchang** [comment]
user reported that fix delivered on 3/16/2015 fixed the problem. Thanks!

**Comment by chanskw** [comment]
Kris, pls target this to 2.0.0 branch and master branch.

**Comment by chanskw** [comment]
Kris, can you please merge the fix in  I have had other reports that people are running into the problem.

**Comment by hildrum** [comment]
If I merge the fix without changes, it will include documentation updates as well.  If that's okay, i can merge it into the master.

**Comment by chanskw** [comment]
I am not sure I understand.. why is documentation update an issue?

**Comment by chanskw** [comment]
Kris, if I merge in the fix, do i have to also manually deliver the fix to the 2.0 branch?  or is that already taken care of?

**Comment by hildrum** [comment]
Reopened to bring fix into 2.0 branch.

**Comment by hildrum** [comment]
fixed in both branches now.
