### ISSUE TITLE
Setup the toolkit directory as a StreamsStudio SPL project.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.inet#11]
I'm trying to setup the toolkit as a Streams Studio Project, here are the steps so far:

1) Clone the Git project
2) Create a new SPL project 'com.ibm.streamsx.inet', unclick Use Default Location and browse to set the Location as the com.ibm.streamsx.inet folder in the cloned Git project.
3) Click Finish
4) Click on 'info.xml' in the project and select **Replace** from HEAD version to replace the info.xml that Streams Studio created, with the one that already existed in the project.

**Comment by chanskw** [comment]
I think this is fixed... I tried cleaning up the SPL Project in Studio and got it to work.
