### ISSUE TITLE
Reset URIList parameter value while the application is running

### ISSUE THREAD

**Issue by hardeys** [IBMStreams/streamsx.inet#121]
Hi, can you provide facility to reset URILIST parameter for the InetSource operator while the application is running. we have a use case of such a feature where the we would like to change the data feed to diffirent URL on the fly.

**Comment by hildrum** [comment]
That's a good idea.  Probably we'd allow InetSource to optionally have an input port that is a list of rstrings, and those rstrings would replace the current set of URIs.  

Another, more flexible option, would be to allow the InetSource to have an input port of any type, and have the URIList be a expression  that can use attributes from the input port.  

If you want to, you can [request a Streams feature](https://www.ibm.com/developerworks/rfe/execute?use_case=changeRequestLanding&PROD_ID=965&).

In the meantime, one work-around is to use a stateful function to provide your URIList.  The DynamicURL sample has a toy example of this.  

But if you made use of the streamx.ps or streamsx.dps toolkit provides a key-value store, you could write an spl function to make use of that.  
Here's a function that uses the streamsx.ps psGet function to get the URIList:
```
list<rstring> getUriList () {
    mutable list<rstring> theList = (list<rstring>)[];
    psGet("uriList",theList);
    return theList;
}
````
Then in your InetSource operator:
`URIList: getUriList()`;`
and elsewhere in your application, use `psPut("uriList", newList);` when you want to change the uriList.

**Comment by hardeys** [comment]
Thanks for your response. Just to get my understanding right. I need to use one of the toolkits specified above to get this function working. When I change URL using psPut("uriList", newList), will the inetSource operator pick it up on the fly or I need to restart the operator to flush out the old value ?

**Comment by hildrum** [comment]
Look at the example `InetSourceDynamicURL`.  In [line 72](https://github.com/IBMStreams/streamsx.inet/blob/master/samples/InetSourceDynamicURL/com.ibm.streamsx.inet.sample/GetNYWeather.spl#L72) of the sample app, we have `URIList: getUrlList()`.  That means that every time a URL fetch happens, `getUrlList()` is called to get the list of urls.  The function `getUrlList()` is a stateful function, returning different values depending on when it called.  On the first fetch, it uses one set of URLs, on the second, a different one, on the third, a different set, and so on.  

If you can write a function like getUrlList that returns the URLs you want to be fetched, then you can use this same technique.   There's multiple ways to write such a function.  Things I can think of:
* use the streamsx.ps or streamsx.dps toolkit, as I described above.
* make getUrlList read a file, and change the url list by updated that file
* write your own getUrlList native function and a corresponding setUrlList native function.

**Comment by joergboe** [comment]
HTTPRequest operator supports variable uri received from input stream
