### ISSUE TITLE
Prepare for a 2.6 release?

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.inet#128]
Wondering if there's interest in a 2.6 release? I've added a couple of JSON operators  ( #125 )  and would like to fix a couple more issues related to JSON and Streams 4.0 (  #123 ).

Any other items people are working on they would like in a release?

**Comment by hildrum** [comment]
+1.  I have no items I'm working on to wait for.

**Comment by ddebrunner** [comment]
I published a 2.6.0 release as a pre-release.

https://github.com/IBMStreams/streamsx.inet/releases/tag/v2.6.0

Once it's had some test we should probably remove the pre-release tag, or produce a new 2.6.x release with any bug fixes.
