### ISSUE TITLE
Reformat code.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.inet#140]
In the rest operators the formatting is a mess, with a mixture of tabs and spaces, making the code really hard to read.

it would  be good to have a convention, at least for spaces/tabs, I would prefer spaces only and four spaces as the indentation level.

If we reformatted all the code to the same standard (Eclipse can do it in one operation), on all branches then it shouldn't be a problem for merging.

**Comment by joergboe** [comment]
This issue is now tracked in:
https://github.com/IBMStreams/streamsx.inetserver/issues/11
