### ISSUE TITLE
error  /usr/bin/ld: can't find -lftpwrapper when building FTPReader application

### ISSUE THREAD

**Issue by sunruns** [IBMStreams/streamsx.inet#144]
I use toolkit com.ibm.streamsx.inet.ftp 2.6 . I use the operator FTPreaer.
   there is an error when building application.
   the error is /usr/bin/ld: can't find -lftpwrapper
![ftpwrapper](https://cloud.githubusercontent.com/assets/11512674/8620988/c4ba3bb4-2755-11e5-8c10-c2e293efcf5a.JPG)

   I can't find libftpwrapper when I search this lib on the internet.
   Could you please tell which rpm i should install? is libcurl-7.19.7-37.el6_5.3.x86_64 ? please tell the requirement of rpm to use ftp.

**Comment by hildrum** [comment]
The library `libftpwrapper` is a part of the toolkit.  It should be in the impl/lib directory of the toolkit.  Did you download the release binaries?  If so, the library should be there already.  If you cloned the toolkit, then you need to go to `impl` and do `make -f Makefile.libftp`
