### ISSUE TITLE
Add checkpoint & consistent region handling for com.ibm.streamsx.inet.rest operators

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.inet#145]
*Injection operators - Not supported in a consistent region, they just accept POST requests, cannot relay their data. No state to checkpoint.

HTTPTupleView - Stateful, should support checkpoint and consistent region. Actually, it should just work, as its state is managed in windows, need to verify. Cannot be a source of a consistent region.

HTTPXMLView - Stateful, should support checkpoint and consistent region & maintain the last tuple seen. Cannot be a source of a consistent region.

WebContext - Stateless, has no ports so by definition cannot be in a consistent region.

**Comment by joergboe** [comment]
This issue in now tracked here:
https://github.com/IBMStreams/streamsx.inetserver/issues/12
