### ISSUE TITLE
Add extra headers parameter to HTTPGetStream and HTTPPost.

### ISSUE THREAD

**Issue by alexpogue** [IBMStreams/streamsx.inet#148]
Some REST APIs require additional headers (e.g. X-Auth-Token for authentication).

There is currently no way to add arbitrary headers to HTTP request operators.

**Comment by chanskw** [comment]
Can you give me an example on how you envision the parameter to look like and how you would use it?  Do you want to be able to provide more than one arbitrary header in a single operator invocation?

Should the header be specified as some key-value pair?

For example, if you want additional header, do you want something like this:

x-header: ["X-Auth-Token":"headerValue", "X-Header2":"headerValue2"]

Would that work?

Thanks!

**Comment by alexpogue** [comment]
@chanskw 

My use right now only requires one extra header, but I'm sure other REST APIs could require more than that.

Yes, key-value pairs would be excellent. I wasn't aware that SPL supported the syntax: ["key1":"value1", "key2":"value2"]

I have something already written that can process a parameter like this:

extraHeaders: ["X-Auth-Token: value", "X-Header2: value"]

Although key-value pairs (as you suggested) would be much better.

**Comment by hildrum** [comment]
SPL will not support that syntax.  For a C++ operator, you could use have a `map<string,string>` and write 
`x-header: {"x-auth-token":"value","X-header2":"value"}`, but I don't believe Java operators are allowed to take maps as input, so you'd have to design your own string structure and then convert to a map.  It could be
`x-header: "X-Auth-Token=headerValue,X-Header2=headerValue2"` which assumes neither header names nor values will contain `=` or `,` or allow x-header to be multivalued, so that it looks like `x-header: "X-Auth-Token=headerValue","X-Header2=headerValue2"` and then you need still assume neither the names nor values will contain `=`.

**Comment by alexpogue** [comment]
I like the multivalued format because then we can still handle values that contain `,`. Although, I also do prefer using `:` to separate the keys and values because that's how headers are normally formatted. Like,
```
x-header: "X-Header1:value", "X-Header2:value"
```

HTTP Header **names** have some character restrictions: they can contain any ASCII characters except:
```
separators     = "(" | ")" | "<" | ">" | "@"
                  | "," | ";" | ":" | "\" | <">
                  | "/" | "[" | "]" | "?" | "="
                  | "{" | "}" | SP | HT
```
([source](http://stackoverflow.com/a/19028585))

From what I understand, though, HTTP Header **values** can contain any ASCII character, so headers like `"User-Agent: Mozilla:4.0"` are possible (note two colons). 

From this fact, all characters before the first "separator" above is the header name, and the rest of the String is the header value.

**Comment by ddebrunner** [comment]
Java operators support parameters with multiple values, so you can have:

xheader: "X-Auth-Token=headerValue", "X-Header2=headerValue2";

That would probably be a better approach than a single string.

**Comment by alexpogue** [comment]
I agree. I have started working on this feature at #153. You may use this as a starting point for whoever will work on it, or give comments for me to fix. Just thought I'd share what I have.

**Comment by joergboe** [comment]
The HTTPRequest Operator implements parameters:
extraHeaders,
extraHeaderAttribute
and accessTokenAttribute

This should be sufficient.
