### ISSUE TITLE
Add HTTPPut operator

### ISSUE THREAD

**Issue by alexpogue** [IBMStreams/streamsx.inet#149]
Some REST APIs need to use the HTTP PUT method to operate as intended (like [Hadoop](https://hadoop.apache.org/docs/r1.0.4/webhdfs.html#Introduction)).

It would be great to have an operator which can interact with these REST APIs.

**Comment by chanskw** [comment]
Can you provide more specific by what you mean to "operate as intended (like Hadoop)"?

Can you give us some sample request?  and what things in the put request you would need to add / customize?  That determines what parameters you may need in this operator.  

The more specifics and information on use case you can give us, the better we can design the operator.

Thanks...

**Comment by ddebrunner** [comment]
Does it make sense to just add a verb parameter to the existing HTTPPost operator, rather than a separate operator?

**Comment by alexpogue** [comment]
@chanskw 
PUT requests are required in order to [write to an HDFS file](https://hadoop.apache.org/docs/r1.0.4/webhdfs.html#CREATE), [make a directory](https://hadoop.apache.org/docs/r1.0.4/webhdfs.html#MKDIRS), [rename a directory](https://hadoop.apache.org/docs/r1.0.4/webhdfs.html#RENAME), among other things. It would be pretty much have the same parameters as the HTTPPost operator.

@ddebrunner 
Yes, that would be a great solution. There would be a small naming issue though. I'd think it strange to use an "HTTPPost" operator that doesn't actually use the POST method. A more generic operator name might be good.

**Comment by ddebrunner** [comment]
Actually since these are Java operators, it would be easy to have common code between HTTPPost and HTTPPut operators, so adding HTTPPut is probably the best way to go.

There might be the need in the future for a generic HTTP operator that does take the method type as a parameter, or even one that takes the method from the tuple, but that could be added when there is some need for it.

**Comment by alexpogue** [comment]
Just a side note, I will also require an HTTPDelete operator [to delete an HDFS file/directory](https://hadoop.apache.org/docs/r1.0.4/webhdfs.html#RENAME) in the near future, in case that effects the decision.

I don't need these operators for what I'm trying to do now, but here's a [list of other HTTP methods](
https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol#Request_methods):
GET, HEAD, POST, PUT, DELETE, TRACE, OPTIONS, CONNECT, PATCH

**Comment by hildrum** [comment]
Note that with  #166 pulled in, there is a way to issue HTTP PUT requests.   As an alternative to creating the HTTPPut operator, it may be possible to create an HTTPPut composite operator using the httpPut function.

**Comment by joergboe** [comment]
HTTPRequest Operator implements also PUT and DELETE operations
