### ISSUE TITLE
Add option to accept all SSL certificates to HTTP operators

### ISSUE THREAD

**Issue by alexpogue** [IBMStreams/streamsx.inet#150]
Some REST APIs have self-signed or unsigned SSL certificates that are rejected by the HTTP operators (for example, see section 4 of [Big Insights doc page](https://www.ng.bluemix.net/docs/#services/BigInsights/index-gentopic1.html#importingdatamethods)). Sometimes the user intends to trust these HTTP connections anyway. The curl command provides the [-k or --insecure](http://curl.haxx.se/docs/manpage.html#-k) flags to accept all SSL certificates.

It would be nice if the HTTP operators provided a similar option.

**Comment by joergboe** [comment]
This param is implemented in HTTPRequest operator. See:
http://ibmstreams.github.io/streamsx.inet/com.ibm.streamsx.inet/v3.0/doc/spldoc/html/tk$com.ibm.streamsx.inet/op$com.ibm.streamsx.inet.http$HTTPRequest.html#spldoc_operator__parameter__sslAcceptAllCertificates
