### ISSUE TITLE
Allow continuous GET Requests

### ISSUE THREAD

**Issue by alexpogue** [IBMStreams/streamsx.inet#152]
HTTPGetStream makes a single HTTP request and then does nothing for the remainder of the Streams app's lifetime. It would be nice to have the ability to make HTTP GET requests periodically.  I imagine a few options to make this work. 
1. Add a "fetchIntervalSeconds" parameter like the one supported by InetSource
2. Add an input port such that every time a tuple arrives, a GET request is made

For option 2, I'm not sure what the appropriate tuple type would be, or whether the tuple's contents should affect the request URI or other parameters. That would be something worth exploring.

I am also not sure whether the HTTPGetStream operator should be modified, or a whole new operator be created for this purpose.

**Comment by hildrum** [comment]
Are both `HTTPGetJson` and `HTTPGetXML` using the wrong data type for you?  The both repeat the request and have parameters for the period and number of iterations.

**Comment by hildrum** [comment]
If I understand correctly, `HTTPGetStream` is meant to be used when, after connecting to the end point, the endpoint will continuously send data.   It's used, for example, with twitter, here:
https://github.com/IBMStreams/streamsx.social/blob/master/com.ibm.streamsx.social/com.ibm.streamsx.social.twitter/TwitterBaseReader.spl

It doesn't really make sense for it to have an input port to "re-get" anything, or if you do, you need to think about what you want to do with the likely-still existing reader when a new tuple arrives.

**Comment by alexpogue** [comment]
Oh, I was not aware of those operators. They might be just what I need.

The continuous data retrieval usage actually makes a lot of sense for HTTPGetStream. Perhaps that's not the right operator for me to be modifying.

One question though: is there a way for the outside world to initiate a GET request (like option 2 mentioned in the first comment), possibly even passing it data with which to make the request? It seems like that would be a useful ability in streams. Is there a reason for choosing to do timed requests instead?

**Comment by hildrum** [comment]
I don't think there is such at operator for GET.

**Comment by hildrum** [comment]
See issue #161.  You could use that in a `Functor` or `Custom` to issue repeated GETs.

**Comment by joergboe** [comment]
See HTTPRequest operator
