### ISSUE TITLE
Code reuse and feature consistency between HTTP operators

### ISSUE THREAD

**Issue by alexpogue** [IBMStreams/streamsx.inet#156]
I am aware of four operators that can make HTTP requests: HTTPPost, HTTPGetStream, HTTPGetJSONContent, and HTTPGetXMLContent

Issue:
Some features ought to be common among all HTTP operators, but not all operators support these features. For example, HTTPPost and HTTPGetStream support authentication, whereas the other two operators do not.

I am also adding more such features (extra headers [#148], SSL acceptance toggle [#154]).

Question: How can I prevent duplicating this code in each operator class? I have listed some solutions I came up with. Feedback / alternative solutions appreciated.

Possible solutions: 
1. Inheritance from some base class HTTPOper: 
   Good: would allow us to define parameters directly on the operators.
   Bad: would require a major refactor because the inheritance trees are so different.
   
   ```
   |- AbstractOperator
      |- HTTPPostOper     <--
      |- HTTPStreamReader <--
      |- TupleProducer
         |- PollingTupleProducer
            |-PollingSingleTupleProducer
               |- AbstractHTTPGetContent
                  |- HTTPGetJSONContent <--
                  |- HTTPGetXMLContent  <--
   ```
2. Implement interface IHTTPOper (without polymorphism): 
   Good: would guarantee existence of _methods_ in implementing classes
   Bad:
   - would not guarantee the existence of _parameters_ on the operators. (unless you can somehow use `@parameter` annotations in interfaces)
   - only purpose of the interface is to force HTTP operators to implement the methods.
   - Implementing IHTTPOper doesn't give any new polymorphic abilities to implementing classes (no incentive to implement it)
   - code duplication in implementing classes
   
   ```
   public interface IHTTPOper {
       void setUrl(String url);
       void setAuthenticationType(String type);
       void setAuthenticationFile(String filename);
       void setAuthenticationProperty(List<String> property);
   }
   ...
   public class HTTPStreamReader ... implements IHTTPOper {...}
   public class HTTPPostOper ... implements IHTTPOper {...}
   public class HTTPGetJSONContent... implements IHTTPOper {...}
   public class HTTPGetXMLContent... implements IHTTPOper {...}
   ```
3. Interface plus helper class (using polymorphism): 
   Good:
   - Interface utilized to potentially reuse code
   - Guarantees _methods_ exist in implementations 
   
   Bad
   - Introduces getters into operators' public API.
   - Does not guarantee _parameters_ exist on the operators.
   
   ```
   public interface IHTTPOper {
       void setUrl(String url);
       void setAuthenticationType(String type);
       void setAuthenticationFile(String filename);
       void setAuthenticationProperty(List<String> property);
       String getUrl();
       String getAuthenticationType();
       String getAuthenticationFile();
       String getAuthenticationProperty();
   }
   ...
   public class HTTPHelper {
       boolean authenticate(IHTTPOper op, ...) {...}
       void addHeaders(IHTTPOper op, ...) {...}
   }
   ```

I am looking for feedback and alternative solutions to this problem. Thanks.

**Comment by ddebrunner** [comment]
I think this is related to issue #45. I don't think the toolkit should be inventing its own http client abstractions when the apache one is in common use elsewhere.

Not sure how that affects your choices.

**Comment by ddebrunner** [comment]
I think the helper object is probably the best approach.

I don't understand this bad though:
>Introduces getters into operators' public API.

**Comment by alexpogue** [comment]
If `IHTTPOper` includes getters in its interface, and `HTTPPostOper` implements `IHTTPOper`, then `HTTPPostOper` must have public getter methods in its implementation. This would expose previously-hidden members of `HTTPPostOper`. Does that make sense?

**Comment by ddebrunner** [comment]
I guess I missed the piece about an interface as well, not sure what it would be needed for, but I don't think that's an issue. The public api is the Java primitive operator, not the class that implements it.

**Comment by alexpogue** [comment]
Are HTTPGetStream, HTTPPost, HTTPGetJSONContent, and HTTPGetXML the only operators that can make HTTP requests?

**Comment by joergboe** [comment]
The operators HTTPPost, HTTPGetStream, HTTPGetJSONContent, and HTTPGetXMLContent are deprecated.
The Operator HTTPRequest combines then into one operator In combination wit an Beacon the HTTPRequest operator can provide all functions of the deprecated operators
