### ISSUE TITLE
HTTPPost Operator: http basic authentication doesn't work (toolkit version 1.2.1)

### ISSUE THREAD

**Issue by ScharffenbergF** [IBMStreams/streamsx.inet#159]
streams version 3.2.0
toolkit version 1.2.1 (Test Release) 
(this is the last version for "old" streams version 3.2.0)

The parameters of the HTTPPost operator are set correctly, the http_auth_basic.properties contains the credentials:

```
stream<HTTPResponse> RESTResponse = HTTPPost(Alert){
    param
        url : "http://sc2-core1/RESTAlert";
        authenticationFile : "http_auth_basic.properties";
        authenticationType : "basic"; 
        headerContentType  : "application/json";
}
```

But the HTTP header doesn't contain the basic authentication header line.

```
POST /RESTAlert HTTP/1.1
Content-Type: application/json
Content-Length: 572
Host: sc2-core1
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.2.3 (java 1.5)
"{"id":"22",  .....  ,"lastUpdateDate":"1381417557448"}"
```

In "HTTPRequest.java" is built the request. But the HTTP request header is build from map "headers" **before** the authentication header is added (auth.sign(this)) to "headers":

```
if(headers.size() > 0) {
    for(Entry<String, String> entry : headers.entrySet()) {
        req.setHeader(entry.getKey(), entry.getValue());
    }
}

//sign the request
auth.sign(this);

return new HTTPResponse(client.execute(req));
```

The line "auth.sign(this);" should be moved up... And then http basic authentication works fine. 

It seems that this issue exists in all newer version...?

regards,
Frank

**Comment by joergboe** [comment]
These operators are deprecated. Use HTTPRequest instead.
