### ISSUE TITLE
httpPost, httpPut, and httpGet native functions

### ISSUE THREAD

**Issue by hildrum** [IBMStreams/streamsx.inet#161]
I'm planning to contribute native functions  for http  post, put, and get to the master branch (which is beta).   The namespace is tentatively com.ibm.streamsx.inet.http, and the function names and prototypes are below: 

In all cases, if username and password are empty, they are ignored.  
`public rstring httpGet(rstring url,list<rstring> extraHeaders, rstring user, rstring password, mutable int32 error)`

`public rstring httpPut(rstring data, rstring url, list<rstring> extraHeaders, rstring username, rstring password, mutable list&lt;rstring> headers, mutable int32 error)`

`public rstring httpPost(rstring data, rstring url, list<rstring> extraHeaders, rstring username, rstring password, mutable list&lt;rstring> headers, mutable int32 error)`

The functions are built using the curl library.  

There's overlap with what we already have, but these aren't duplicates.   The fact that they are functions means they can be used in ways where it'd be awkward to use an operator.   For example, to build access to webhdfs via the knox gateway, you'd need to issue a put request, read the location header, and then do another put request.  Likewise, using a hbase scanner via the stargate interface requires that you read a location header and then use that as your URL.  

I've used these to build prototype SPL operators for reading from and writing to webhdfs.

Comments, particularly on the naming, are appreciated.

**Comment by ddebrunner** [comment]
The naming conventions for SPL functions is to use camel case.
http://www-01.ibm.com/support/knowledgecenter/SSCRJU_4.0.1/com.ibm.streams.dev.doc/doc/str_namenativfunc.html?lang=en

**Comment by ddebrunner** [comment]
Using blob as the content type seems restrictive, doesn't most HTTP data better fit a rstring? E.g. application/json is a typical content type for data which would be better represented as `rstring`.

From the experience with the operators, it does seem that mime type specific versions are useful, especially for developers, e.g. `httpGetJson(...)`.

**Comment by hildrum** [comment]
Camel case it is, then.   I'll also change to using `rstring`, since I think you're right that that's the usual case.  

I think it's better to keep the native functions type-general.   In building webhdfs operators, they need to be.    But I can include  `httpGetJson` & `httpGetXml` spl functions wrapping the native functions.

**Comment by hildrum** [comment]
Any thoughts about whether I should also include base64Encode and base64Decode functions?  I wrote them for the rest API for HBase.  I think I'm going to put the HBase-specific stuff in a different toolkit than the Inet toolkit, but I'm not sure whether to consider base64Encode and base64Decode as HBase specific or whether they'd be generally useful enough to go in the inet toolkit.

**Comment by hildrum** [comment]
I also added a httpDelete, URLencode and URLdecode.

**Comment by chanskw** [comment]
With this contribution, I am starting to wonder where we draw the line as to when we create operators and when we create native functions.

The Inet toolkit already has an operator called HTTPPost, why do we want a native function for httpPost?  and would that be too confusing?

In addition, how do we decide that these requests should be functions and not operators.  The rest of the toolkits have operators for get  and post requests, whether it's HTTP or FTP, why do we want to break away from that pattern?

**Comment by scotts** [comment]
I tend to prefer native functions for places where native functions are possible. That allows them to be used in more and unanticipated ways. It allows full flexibility: they can be used in part of a larger operator, or they can just be wrapped up in a Custom and presented as-is as an operator.

Writing native functions is simpler and easier than writing new primitive operators. The programming model for exposing a native function is straight-forward. Writing a Custom operator requires learning the stream programming model, but users are helped by the language. However, dropping down to implementing logic as a primitive operator requires understanding more about the internals of the streaming model, which are abstracted by the language.

If possible and reasonable, I prefer to expose functionality through native functions, and wrap those up in Customs. (Of course, this will not always be possible and reasonable.) This pattern has helped in the past with new users who were still trying to understand the streaming model, and I find it desirable because it allows for more reusability and flexibility.

**Comment by hildrum** [comment]
One general advantage is that native functions is they can be wrapped into a composite to look like an operator, or you can use them to perform a potentially complex series of operations in Custom.  

Consider, for example, interacting with the webhdfs gateway to do a write.  First you need to do a put, then take the location header from the result of that, and then do another put with that new URL.  This would be awkward as a series of operators, but is pretty simple set of commands inside a Custom operator and it maps very closely to what'd you'd see if you looked up for directions on how to do this using the command line.  
````
   // $baseUrl, $file, and $overwrite are composite parameters
    rstring createUrl = $baseUrl+"/"+$file+"?op=CREATE&overwrite="+(rstring)$overwrite;
    mutable list<rstring> headers = (list<rstring>)[];
    mutable int32 error = 0;
    rstring newFile= httpPut(emptyBlob,createUrl,(list<rstring>)[],username,password,headers,error);
    rstring location = getLocation(headers);  // this function just returns the value of the location header by 
                                              // searching through the list.
    rstring exception = httpPut(data,location,(list<rstring>)[],username,password,headers,error);
````

A second reason in this particular case is that our current HTTP operators are java operators.  That means that the URLs used cannot be general expressions (eg, `baseurl + "/"+tablename+"/"`).  The native functions can be used in this way.  

I believe these to be useful building blocks.  With httpGet, you could build your own Customized InetSource, or an InetSource-like operator that takes a URL as input.  I've used these native functions to interact both with the webhdfs and with the REST API for HBase.  I suspect that they (or slight improvements) could be used for other REST API applications. 

I don't think we need to choose between an httpPost native function and an HTTPPost operator; why not have both?

**Comment by mikespicer** [comment]
I think both have their place and we should choose the most appropriate one when there is a clearly better choice and provide both when there are use cases for both.  Native functions are easier to implement and do allow more flexibility where multiple functions can be used in the logic of a custom to  achieve a specific task from generic functions.  However, requiring a user to wrap lower level functions in a custom for tasks that fit well as an operator on a stream is burdensome.  Always providing both functions and operators would be more confusing but this seems like a case of making the simple simple and the complex possible where the operators work well for simple cases and the functions allow more complex logic.
