### ISSUE TITLE
Ant build script should build the samples

### ISSUE THREAD

**Issue by joergboe** [IBMStreams/streamsx.inet#172]
Hello,

I found that the build.xml script does not compile the samples. It calls only the indextoolkit target.

I think the ant all command should also build all samples ans vice versa the clean target should clean all samples.
All samples have makefiles so this should not cause problems.

I can provide the fix for that.

**Comment by chanskw** [comment]
Hello,

I think this is done intentionally.  When we build and package the toolkit for a release, we do not build the samples.  The samples are shipped as source code and it is expected that when clients want to try it out, they will build this.  Building the samples as part of release package could potentially increase the package size.  And if the samples refer to C++ operators, then to build a release with the samples pre-built, we will need to build on all supported platforms.

However, if it's not already present, i think it makes sense for the top ant script to have a build-all-samples target.  It will make it easier to build all the samples.

If you want the "all" target to build the samples too, then perhaps we will probably need a target that will only build the toolkit, and index the samples, like we currently have.

Thanks...

**Comment by joergboe** [comment]
Hello,

ok. So we should add 2 targets build-all-targets and clean-all-samples.
The taget all should be unchanged and build the toolkit index for all 
samples
The target clean should include the clean-all-targets.


Additionally: The toolkit already built a shared library which includes 
FTPWrapper and httpFunctions. So do we need to provide a package for every 
platform anyway?

Regards
