### ISSUE TITLE
Clarify certificateAlias and how it is used

### ISSUE THREAD

**Issue by bmwilli** [IBMStreams/streamsx.inet#174]
##### certificateAlias

Alias of the certificate to use in the key store. When this parameter is set all connections use HTTPS.

I cannot find any additional information. I set it to the value "IDONOTKNOW" in all of my HTTPTupleView and WebContext operators (along with all of my certs and passwords) and everything seems to work fine.  

So it left me wondering what its purpose is.

**Comment by ddebrunner** [comment]
It's the alias in the key store of the certificate to use to identify the web-server's identity.

Not sure what is happening in your case, I'd have to mess around with it, I only tried with a valid setup.

**Comment by joergboe** [comment]
This is moved to: 
https://github.com/IBMStreams/streamsx.inetserver/issues/3
