### ISSUE TITLE
Running on Streams for PPC

### ISSUE THREAD

**Issue by bmwilli** [IBMStreams/streamsx.inet#175]
I am attempting to use this toolkit on the Power PC using Streams 4.0.1.0 under Redhat 6.  The SimpleInject sample compiles and runs.  When I attempt to access its main page "http://myhost:8080" the browser just hangs.

I turned on Trace, and I can see the createEndPoint() was called, however, that is all that shows.  I never see the HttpParser.parseNext call or anything after that.

Any ideas what could be wrong?

Has anyone run this sample on Streams for PPC?

Thanks,
Brian

**Comment by conglisc** [comment]
Hi Brian,

Which version of inet toolkit are you using? Did you download from release page or you built it yourself off master branch.

I used https://github.com/IBMStreams/streamsx.inet/releases/tag/v2.7.0 running on 4.0.1.0 and the main page comes up right away without any issues.

Thanks

**Comment by bmwilli** [comment]
It was the product release in 4.1. The version from github worked just fine

----------------------------------
Brian M Williams (from iPhone)
Executive IT Architect Big Data
IBM Software Services Federal
301-803-2021

**Comment by bmwilli** [comment]
I am sorry, I have your message confused with a PMR I had open.  Please 
disregard my previous reply.  As for inet toolkit on PPC, I submitted two 
fixes which allow it to work just fine.  One of the main issues was only 
found if you ran on PPC with a great number of processors.  Our nodes had 
256 processors and it caused a problem with the Jetty server.

The other problem was compiling it on PPC, and I edited the Makefile to 
use the Advanced Toolchain compiler.

Both of those changes were added to the baseline by Dan Debrunner several 
weeks ago.

Brian
----------------------------------
Brian M Williams
Executive Certified IT Architect
IBM Software Services Federal
301-803-2021

**Comment by conglisc** [comment]
Hi Brian,

Thanks, so I assume this issue can be closed?

**Comment by bmwilli** [comment]
Yes.  Closing.  Thanks
