### ISSUE TITLE
trace/debug statements logged at INFO level

### ISSUE THREAD

**Issue by ejpring** [IBMStreams/streamsx.inet#176]
There are a lot of "trace.log(TraceLevel.**INFO**, ...)" statements in this toolkit that I think should be "trace.log(TraceLevel.**DEBUG**, ...)" statements, especially those in the process() method. Is there a reason they aren't?

**Comment by ejpring** [comment]
I've submitted a pull request that changes the LogLevel of tracing messages in the WSServer process() methods from INFO to TRACE. This improves performance by eliminating file I/O from the main loop of applications that use the WebSocketSend operator.

**Comment by ddebrunner** [comment]
Thanks for the fix!

**Comment by ejpring** [comment]
Thanks for merging it!
