### ISSUE TITLE
Allow specification of the server (host) to listen on for HTTPTupleView and related operators. 

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.inet#18]
Current the Jetty webserver is listening on all network interfaces, this caused an issue when some of the network interfaces were running at full throughput, with traffic unrelated to the Jetty operators.

**Comment by joergboe** [comment]
This issue is now tracked here:
https://github.com/IBMStreams/streamsx.inetserver/issues/7
