### ISSUE TITLE
Shouldn't the 2.7.0 version include earlier versions' operators and functions?

### ISSUE THREAD

**Issue by Chirux** [IBMStreams/streamsx.inet#184]
I don't know if it's only when I try to use the toolkit or if anyone else encounters the same problem, but in version 2.7.0 I would like to be able to use the operators that were included in version 2.6.0 (HTTPGetStream() etc.), but in 2.7.0 only the functions httpGet() etc. is included.

**Comment by ddebrunner** [comment]
I would have thought they should be there.

**Comment by Chirux** [comment]
Sorry, my bad, I installed the toolkit in the wrong way!

Thanks anyway!

**Comment by ddebrunner** [comment]
@Chirux Thanks for the update!
