### ISSUE TITLE
Streams 4.1 Support Websocket

### ISSUE THREAD

**Issue by murphydlm** [IBMStreams/streamsx.inet#185]
I need the Websocket support for Streams 4.1. Is there a 4.1 release supporting Websockets?

**Comment by siegenth** [comment]
I believe the version that is being used in 4.0.1 (2.7.0) will work with 4.1. I have not tried it since I'm currently in a 4.0.1 environment. Or, are you seeing a problem?

**Comment by murphydlm** [comment]
I will try it. I just didn't see a version that specified 4.1. I will try 2.7 on the new release. 

Dan Murphy
Big Data
636-346-3166


   siegenth --- Re: [streamsx.inet] Streams 4.1 Support Websocket (#185) --- 
    From:"siegenth" <notifications@github.com>To:"IBMStreams/streamsx.inet" <streamsx.inet@noreply.github.com>Cc:"Daniel L Murphy" <murphyld@us.ibm.com>Date:Tue, Jan 12, 2016 4:03 PMSubject:Re: [streamsx.inet] Streams 4.1 Support Websocket (#185)
  
  I believe the version that is being used in 4.0.1 (2.7.0) will work with 4.1. I have not tried it since I'm currently in a 4.0.1 environment. Or, are you seeing a problem?

**Comment by murphydlm** [comment]
Martin,

Tried it and it works fine 2.7 works with 4.1.

                                                                       
                                                                       
                                                                       
 Dan Murphy                                                            
 TSS                                                                   
 IBM Analytics                                                         
                                                                       
 Phone: 636-346-3166                                                   
 E-mail: murphyld@us.ibm.com                                           
                                                                       
                                                                       
                                                                       











From:	siegenth <notifications@github.com>
To:	"IBMStreams/streamsx.inet" <streamsx.inet@noreply.github.com>
Cc:	Daniel L Murphy/Springfield/IBM@IBMUS
Date:	01/12/2016 04:03 PM
Subject:	Re: [streamsx.inet] Streams 4.1 Support Websocket (#185)



I believe the version that is being used in 4.0.1 (2.7.0) will work with
4.1. I have not tried it since I'm currently in a 4.0.1 environment. Or,
are you seeing a problem?


—
Reply to this email directly or view it on GitHub.
