### ISSUE TITLE
Bash testing

### ISSUE THREAD

**Issue by jchailloux** [IBMStreams/streamsx.inet#186]
I'm unable to test the SampleInject.spl using nc

(echo 'POST /InjectedTuples/ports/output/0/inject HTTP/1.1'; echo 'Host: localhost'; echo 'Content-Type: application/x-www-form-urlencoded'; echo; echo 'a_ustring=aaa&b_rstring=bbbb&c_int32=1&d_float32=2.2' ) | nc xxx.xxx.xxx.xxx 8123
HTTP/1.1 204 No Content
Server: Jetty(8.1.3.v20120522)

HTTP/1.1 400 Bad Request
Content-Length: 0
Connection: close
Server: Jetty(8.1.3.v20120522)

http://localhost:8123/InjectView/ports/input/0/tuples gives me 
[{"a_ustring":"","b_rstring":"","c_int32":0,"d_float32":0.0},{"a_ustring":"","b_rstring":"","c_int32":0,"d_float32":0.0}]

What do I missed ?

**Comment by ddebrunner** [comment]
It looks like the POST request is being seen, but its contents are not in the correct format.

You can try using one of the many POST testers available as a browser plugin.

**Comment by jchailloux** [comment]
Agree post was seen but wanted to test using basic command.

We use telnet host 80 to test web servers. wanted to do the same for POST with Streams. Running Streams on an OS without UI and no way to test from outside until all processes are ok. So only this local test will permit me to validate.

**Comment by ddebrunner** [comment]
I would test the nc command in a simple environment, running on a laptop with Quickstart VM.

Or see if you can compare the contents of the POST request you are sending with one generated from a posting browser plugin.

**Comment by joergboe** [comment]
I think the post method must have a content length header like:
Content-Length: 42\r\n
