### ISSUE TITLE
HTTPPost accept jsonString as-is

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.inet#187]
If the sole attribute is `rstring jsonString` and the content type is `application/json` then send the value as JSON, not as a SPL tuple converted into JSON.

**Comment by ddebrunner** [comment]
Similar, if an attribute is `rstring jsonString` then the value should be taken as-is.

E.g. with this schema from streamsx.iotf

`rstring deviceType, rstring deviceId, rstring eventId, rstring jsonString`

**Comment by ddebrunner** [comment]
Proposing supporting direct JSON using `rstring jsonString` when:
* it's the only attribute in the input schema
* it's a top-level attribute in the input schema, e.g. `rstring deviceType, rstring deviceId, rstring eventId, rstring jsonString`

With `rstring deviceType, rstring deviceId, rstring eventId, rstring jsonString` the behaviour would be:

The jsonString is assumed to represent a JSON object and is converted to a JSON object `J`.
For each other attribute it is converted to JSON and added to `J` using the attribute name.

So there would be a JSON object with keys `deviceType`, `deviceId`, `eventId` and the keys represented in `jsonString`.

**Comment by joergboe** [comment]
The HTTPRequest Operator implements parameter:
requestBodyAttribute

    Request body attribute for any method that accepts an entity (PUT / POST / PATCH). In method PUT and PATCH the body of request is taken from this attribute. In method POST, any non-empty value overwrites the request attributes. 

This means the Operator builds the Method entity either from tuple attributes or from the requestBodyAttribute. There is no mixing. I think this is sufficient.
