### ISSUE TITLE
contentAttribute parameter defined in HTTPGetJSONContent operator result in compile error

### ISSUE THREAD

**Issue by conglisc** [IBMStreams/streamsx.inet#189]
According to spldoc, contentAttribute is defined for specifying output attribute to assign content to, and internally this parameter is represented with TupleAttribute<Tuple, String>.

When HTTPGetJSONContent is specified with a contentAttribute, the compiler is actually looking for the attribute from the input port schema, I think this parameter is not doing what it was expected to do.

For example, following definition of HTTPGetJSONContent operator results in compile time error

```
> (stream<rstring jsonString> HTTPGetJSONContent_1_out0) as
>           HTTPGetJSONContent_1 = HTTPGetJSONContent()
>       {
>           param
>               url : $serverURL ;
>               initDelay : $initDelay ;
>               iterations : $iterations ;
>               period : $period ;
>               acceptAllCertificates : $acceptAllCert ;
>               contentAttribute : jsonString ;
>       }

```

CDISP0053E ERROR: An unknown identifier was referenced in the SPL program: jsonString.

**Comment by joergboe** [comment]
Yes it makes no sense to define a parameter with ExpressionMode: Attribute and there is no input port possible. This operator is deprecated use HTTPRequest instead.
