### ISSUE TITLE
WebSocket Clients

### ISSUE THREAD

**Issue by hardeys** [IBMStreams/streamsx.inet#192]
Hi , Any plans to provide web socket clients  as part of iNet toolkit ?

Does the WebSocket Inject operator submits a Punct every data packets received  ?

**Comment by siegenth** [comment]
Hello:

Adding a WebSocket client makes sense, but I've got no plans/time to add this feature. Would welcome contribution of such functionality. 

The Inject does not add a punctuation. Would the Punctor operator satisfy your requirements? Pass the Inject output through Punctor.
