### ISSUE TITLE
FTP operators shall support forwarding of input values to the error port

### ISSUE THREAD

**Issue by m-kotowski** [IBMStreams/streamsx.inet#193]
Today, the FTP operators offer an error port that must have a single rstring attribute as schema. Error messages are assigned in English to this rstring attribute. The error messages are fixed, for example:

"_libcurl perform operation failed! curl says: Couldn't connect to server url:ftp://unknownhost/directory_"

The proposal is to support the following custom output functions as well as automatic and manual assignments from input attributes to output attributes to support an improved error handling.
1. T AsIs(T) - Returns the provided argument as-is. The argument can be an input attribute or a constant value. This function is the default function.
2. rstring Message() - Returns the message string, which is the string that is returned today in the single rstring attribute.
3. additional functions that make sense like ErrorCode() returning errno or a function that returns the cURL message only (without operator-specific prefix)

To stay compatible, if no custom output function is provided in the output clause for the error port, the old behavior is active, which means: only a single rstring attribute is supported.

**Comment by ddebrunner** [comment]
> To stay compatible, if no custom output function is provided in the output clause for the error port, the old behavior is active, 

Be interesting to see if this can be done. I think from the operator's point of view then no output clause will be seen as all output attributes matching input attributes are set using AsIs (the default function). Though maybe only supporting the single output attribute in this case helps.

**Comment by joergboe** [comment]
The operators have now a new set of output functions which may be used for the error port.
These Functions are:
- Error
- ErrortText
- Url
- NoTransfers
- NoTransferFailures
- NoBytesTransferred
- AsIs
If none of these functions is used the old functionality is used.

**Comment by ddebrunner** [comment]
I assume 'NoTransfers' means the number of transfers, but I had to think about it. E.g. why not NumberTransfers? Why only abbreviate Number?

Is there an existing convention (existing operators) for how 'number' is abbreviated?

**Comment by joergboe** [comment]
Yes No mean number. You can say that this is not nice.
But in the GetData Function group there these functions NoTransfers, NoTransferFailures, NoBytesTransferred, exists for a long time. I would propose to keep this names as they are to avoid incompatible changes.

**Comment by m-kotowski** [comment]
I also prefer names without abbreviations. So, what about deprecating the NoXXX and introducing functions with names that are easier to understand?

For the 3 functions, the "No" could be removed and the meaning would be still understandable, TransferCount and TransferFailureCount would be also fine.

Btw, "Transfer" fits for the Put operator and the Reader operator in FileSource mode, but it does not fit for the Reader operator in directory scan mode and also not for the command operator. Perhaps, we can find a better prefix?

And, I would also rename Error to ErrorCode - clearer that a code is returned and not sth else, like error count, error text, error flag (yes/no), etc.

**Comment by joergboe** [comment]
Ok
I will deprecate:
Error
NoXXX
and add new Functions/Aliases
- ErrorCode
- TransferCount
- TransferFailureCount
- BytesTransferred
