### ISSUE TITLE
WebSocketInject operator should not perform String reference comparison between the value specified via messageAttribute and output port schema attribute name

### ISSUE THREAD

**Issue by conglisc** [IBMStreams/streamsx.inet#194]
When WebSocketInject has only 1 attribute in output port schema and messageAttribute specifies the same attribute name as the message attribute, the operator fails with following error message

java.lang.IllegalArgumentException: Attribute 'data' expected, found messageAttribute value 'data' - invalid attribute name.
    at com.ibm.streamsx.inet.wsserver.WebSocketInject.produceTuples(WebSocketInject.java:178)
    at com.ibm.streamsx.inet.wsserver.WSServer.onMessage(WSServer.java:93)

This is caused by the WebSocketInject operator performing string reference comparison rather than comparing content as written in line 177 of WebSocketInject

```
if (out.getStreamSchema().getAttributeCount() == 1) { // port only 1 attribute          
                attrMsgTypeName = out.getStreamSchema().getAttribute(0).getType().getLanguageType();                
                attrMsgName = out.getStreamSchema().getAttribute(0).getName();
                if ((messageAttrName != null) && (messageAttrName != attrMsgName)) {
                    throw new IllegalArgumentException("Attribute '" + attrMsgName + "' expected, found messageAttribute value '" + messageAttrName +"' - invalid attribute name.");                    
                }
```

where it checks (messageAttrName != attrMsgName).

**Comment by joergboe** [comment]
This issue is now tracked here:
https://github.com/IBMStreams/streamsx.inetserver/issues/13
