### ISSUE TITLE
issue on FTPreader binary

### ISSUE THREAD

**Issue by sunruns** [IBMStreams/streamsx.inet#196]
hi, when i use ftpreader binary to download a zip file (size 68759277) from remote server, and then filesink to a file in local file system, but the file size is 68792853 , and the remote binary file is read into 4197 tuples , 68759277 + 4197*8 = 68792853. so I think streams add 8 bytes after each tuples of binary. How to resolve this issue? Is there method to define the blob size of libcurl? how to eliminate the 8 bytes in each blob?
```
stream Signaloutput as OUT = FTPReader( FilenameStream as IN) { 
     param 
      protocol : ftp; isDirReader : false;
      path : "./Desktop/zipfile/";
     filename : IN.fileName; username : "streamsadmin"; password : "passw0rd"; host : "localhost";     
    curlVerbose : true; output OUT :
     fileblob = Binary(); 
   }
   () as Writer = FileSink(Signaloutput) { 
            param file : "zipfile.gz"; 
            format : bin;
            writePunctuations : false; 
   } 
```

**Comment by ddebrunner** [comment]
Have you tried block format on the FileSink?

**Comment by sunruns** [comment]
yes, it works after change format to block in filesink.
