### ISSUE TITLE
HTTPPost: forward input stream attributes

### ISSUE THREAD

**Issue by anand-ranganathan** [IBMStreams/streamsx.inet#198]
Ideally, it would do the following:
a. Forward any input stream attributes as dictated by output schema
b. Takes a list of attribute names to construct the HTTP Post request.

**Comment by ddebrunner** [comment]
Split original issue into two issues, this and #199

**Comment by joergboe** [comment]
New operator HTTPRequest implements this concept and can be used as replacement of HTTPPost.
Release Inet toolkit 2.9.5
