### ISSUE TITLE
HTTPPost: allow subset of input stream attributes to be used in the request.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.inet#199]
Takes a list of attribute names to construct the HTTP Post request.

(split out from issue #198)

**Comment by ddebrunner** [comment]
Should take a look at what HTTPTupleView does as there are two approaches, with the possibility to support both:

* Explicit list of input attributes to use
* List of input attributes to skip from the request.

**Comment by joergboe** [comment]
The HTTPRequest operator supports this concept with parameter requestAttributes
