### ISSUE TITLE
Timeout and number of retries parameter for HTTPPost

### ISSUE THREAD

**Issue by anand-ranganathan** [IBMStreams/streamsx.inet#200]
Currently the HTTP Post operator seems to get stuck or drops the tuple if it's not able to reach the server or if there is any connection error.  It should be able retry a few times and finally emit an error tuple if this happens.

**Comment by siegenth** [comment]
There is a maxRetries on current latest checked in version (2.7.3), here is sample of it being used....
```
		(stream<rstring name, int32 id, int32 debt, rstring data, rstring errorMessage, int32 responseCode, int32 dataSize> HTTPPost_4_out0) as HTTPPost_4 = HTTPPost(Beacon_3_out0
			as InputStreamName0)
		{
			param
				url : "http://9.72.139.122:8080/jettyDev2_war_exploded/venus" ;
				headerContentType : "application/json";
				maxRetries : 10;			
		} 
```
The problem I'm seeing, the default timeout for connecting is 60 seconds.  Adding a parameter that sets the connection timeout seems appropriate. I propose to add a connectionTimeout parameter, with units of millisecond. If it's not set we go with the default, currently 60000.

If you attempt to connect to a nonexistent website (ie: empty.drum.org) you get back an error immediately and it retries up to maxRetries - using the retryDelay or it's default. That is, attempting to connect to a nonexistent website and trying to connect to a down website have different timeout characteristics.

**Comment by ddebrunner** [comment]
Most operators using a float64 as time value, and then Java code internally converts it to milliseconds. 
E.g. 30.0 would be thirty seconds.

**Comment by siegenth** [comment]
More investigation reveals that the code does not actually handle the TCP connections failure. The maxRetries is exhausted, the exception is thrown in the process method.  The process method is retried until the retry count is exceeded, then a shutdown occurs.

**Comment by joergboe** [comment]
The HTTPRequest operator works this way.
