### ISSUE TITLE
Forward input stream attributes even in case of exceptions/errors

### ISSUE THREAD

**Issue by anand-ranganathan** [IBMStreams/streamsx.inet#201]
This is an extension to issue #198 , where input stream attributes must be forwarded in an output tuple even when there are failures in processing that input tuple, such as connection exceptions.

**Comment by siegenth** [comment]
Makes sense. The output's 'responseCode' and 'dataSize'  indicate that their was a problem. The consumer is responsible for recognizing the the values not copied from the input are invalid.

**Comment by joergboe** [comment]
The new operator HTTPRequest implements this requirement and can be used as replacement of HTTPPost (release 2.9.5)
