### ISSUE TITLE
Test failure HTTPStreamBasicFunctionTestMain

### ISSUE THREAD

**Issue by kmarsden** [IBMStreams/streamsx.inet#204]
I am seeing a test failure running ant tests which is likely a user error, but need some guidance. 

[exec]  [Bundle] com.ibm.streamsx.inet.http.tests.HTTPStreamBasicFunctionTestMain.sab
     [exec] ./scripts/testRunner.sh ./output/HTTPStreamBasicFunctionTestMain/bin/standalone `./scripts/getProps.sh data/http.properties com.ibm.streamsx.inet.http.tests::HTTPStreamBasicFunctionTestMain`
     [exec] ERROR: Test Failed
     [exec] make: Leaving directory `/homes/hny1/kmarsden/git/streamsx.inet/tests/tests.http'
     [exec] make: **\* [HTTPStreamBasicFunctionTestMain] Error 1
     [exec] Result: 2

The file http.properties just has 
baseUrl=http://host:port

Do I need to setup a jetty server and put the url in this file  or is there some other setup that is needed for the tests?

**Comment by ddebrunner** [comment]
I think it's the same issue as #141 

Someone set up some of the tests but didn't leave any instructions on how to run them.

**Comment by joergboe** [comment]
These test are deprecated and produce false positive results even if the server is not activated.
The InetSource operator test and URLEncode & Decode tests are now covered from framework tests.
HTTPPost ang GetsStream are deprecated
see pr #341
