### ISSUE TITLE
info.xml is missing namespaces on master

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.inet#205]
Originally had the full set of namespaces:
https://github.com/IBMStreams/streamsx.inet/blob/202594202eb94a1ea2c5fcc0a87cb2b18e7bea31/com.ibm.streamsx.inet/info.xml

This commit incorrectly removed some.

https://github.com/IBMStreams/streamsx.inet/commit/769214c3726b35b54758139aa3c23d87f177d32a#diff-a5efc00564655822a9b7f324dc3b503a

**Comment by joergboe** [comment]
I think this can be cloded
