### ISSUE TITLE
Enhance HTTPPost() or create a HTTPGet()

### ISSUE THREAD

**Issue by siegenth** [IBMStreams/streamsx.inet#210]
The HTTPPost operator has an input port that provides values which are sent to the HTTP POST request. Each invocation can provide different values.  It turns out, some BlueMix service(s) expose functionality only via  HTTP GET, a GET I need to modify, with an input parameter, on each invocation. 

The HTTPGetStream(), HTTPGetXML() and HTTPGetJSONContent() operators invoke an HTTP GET with a static set of parameters. This is not adequate. In addition, the invocation cannot be 'on demand', 
it's on a timer. 

I'd like/need/request a HTTPGet()  similar to the HTTPPost. Where the values are extracted from the input port.

Two possibilities that I have come up with...;
-  Add an additional parameter to HTTPPost(). A parameter that will invoke a HTTP GET in lieu of a HTTP POST when present. 
- Add a new operator HTTPGet() that has majority of the parameters of HTTPPost(). A parameter that would not exits on the HTTPGet() and is on the HTTPPost() is headerContentType. 

Example proposed operator usage  - queries are being sent to the BlueMix Twitter service, querying for candidate names in tweets : 'clinton', 'trump', 'bush'....

```
        stream<rstring q, rstring size> Source = Beacon()
        {
            logic 
              state: {
              mutable int32 idx = 0;
              list<rstring>queryTerms = ["clinton", "trump", "bush","cruz", "paul", "rubio","siegenth"]; 
            }
            param
                period : 10.0 ; iterations : 20  ;
            output
                Source : q = queryTerms[(idx++) % size(queryTerms)], size = "100" ;
        }

        stream<HTTPResponse> Get = com.ibm.streamsx.inet.http::HTTPGet(Source)
        {
            param
                url : "https://cdeservice.mybluemix.net:443/api/v1/messages/search" ;
                authenticationType : "basic" ;
                authenticationProperty : "userid=" + getSubmissionTimeValue("username"),
                    "password=" + getSubmissionTimeValue("password") ;
        }
```

**Comment by ddebrunner** [comment]
Maybe a generic HttpMethod/HttpInvoke operator that can also (optionally) take the type of the request from the tuple.

So additional parameters of:

`method:` method to use, e.g. POST, GET (using an enum)

`methodAttribute`: attribute that defines the method to use (using same enum)

`method` and `methodAttribute` are mutually exclusive.

(parameter names could be improved)

https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol#Request_methods

**Comment by siegenth** [comment]
Lets see if I understand what you're saying:
Create a HTTPInvokeMethod() that accepts the following verbs : POST, GET (DELETE, PUT, HEAD, TRACE... in the future).  The verb can appear on the input stream as an attribute of 'method' or as a parameter called 'method' which are mutually exclusive. 

Should we not be doing the same for url, adding it as a possible attribute as well? This would allow
us to have more dynamic connection, connect to different hosts, enable fallback processing on failed connections. 

I like having separate operators HTTPPost()  HTTPGet() - I look at the name and I know what it's going todo, having to look down to parameter or look at the upstream to work out how the portion of the 
Stream is going to be processed. Is it easier to remember a bunch of operators or remember a bunch of parameters for a operator. 

But... HTTPInvokeMethod() would make adding the DELETE, PUT, HEAD... functionality easy in the future.

**Comment by BruceGlassford** [comment]
While we're at it - adding certificate support here would be nice - I don't see it in the latest release. And let me add a +1 for the URL being passed in to whatever ends up being built - either a generic invoke or a fancier Get.  (At least parameterize the URL so I can access semi-RESTful interfaces).

**Comment by ddebrunner** [comment]
See proposal:
https://github.com/IBMStreams/streamsx.inet/wiki/HTTPRequest-operator
