### ISSUE TITLE
FTPreader read duplicate filename if scan at the second time

### ISSUE THREAD

**Issue by sunruns** [IBMStreams/streamsx.inet#211]
If  the triggerstream triger the ftpreader to scan the directory, the same filename will be output again. 
the directory on the ftp server is a hot directory, thats to say there are always new files writing .
how to resolve this problem?

```
stream<uint32 tag> TriggerStream = Beacon()
        {
            param           period :  60.0;
            //iterations : 1 ;
            output
                TriggerStream : tag = 1u ;
        }
```

stream<rstring fileName, uint64 size, rstring date, rstring user, boolean isFile> FilenameStream as OUT = FTPReader(TriggerStream) {
    param
        protocol : ftp;
        isDirReader : true;
    output OUT :
}

**Comment by joergboe** [comment]
Hi,

if the FTPReader is used as a directory scanner the files are reported as long as the files are there. This operator does not implement the full functionality of the DirectoryScan.
The resolution depends on your requirements.
In a typical use case the files are removed/moved after the processing of that file. This can be achieved with the FTPCommand operator. The sample 'RemoteDirScanAndGet' shows the sample code for this scenario. 
If you have not the possibillity to move/remove the files, then you must implement a custom filter operator which maintains the list/map of the already known files, sizes and ftimes and you must implement a housekeeping logic for that list/map. You can remove files from that list when they are not any longer seen in the directory. But you must take care in case of interruptions of scan operations. Interrupted scan operations should not trigger a clean up.

**Comment by joergboe** [comment]
Since there is no response since a long time I would close
