### ISSUE TITLE
HTTPTupleView - add jsonP wrapper

### ISSUE THREAD

**Issue by BruceGlassford** [IBMStreams/streamsx.inet#212]
Enhancement

Some javascript implementations are supporting JsonP - which has a "callback" function.  Suggested enhancement for HTTPTupleView is to detect a ?callback=myfunction parameter on the request and wrapper the returned json in myfunction(.....returnedjson...); to support this callback.

**Comment by ddebrunner** [comment]
For reference:
https://en.wikipedia.org/wiki/JSONP

**Comment by joergboe** [comment]
This issue is now tracked here:
https://github.com/IBMStreams/streamsx.inetserver/issues/14
