### ISSUE TITLE
REST operators - provide ability to specify additional headers

### ISSUE THREAD

**Issue by BruceGlassford** [IBMStreams/streamsx.inet#213]
HTTPTupleView/XMLView as well as the Injection operators (not 100% sure it's needed on the latter).  Add an extraHeaders parameter of the form list<String> that would accept additional http headers in the form "header:value" to be output by the operators.   This will enable the user to specify CORS headers, for example, or any other specialized header required.

**Comment by brucegdc** [comment]
Can be closed - solved by pull merged in 2016  https://github.com/IBMStreams/streamsx.inet/pull/223
