### ISSUE TITLE
Unable to write the bluemix cloudant from streams using HTTPost

### ISSUE THREAD

**Issue by hardeys** [IBMStreams/streamsx.inet#216]
Hi Team, 

I am unable to write to bluemix cloudant service from streams. During my analysis, what is found that streams HTTPost operator can not work with long username strings in the URL 

e.g. https://874c7f51-7e05-4154-8844-d5efada28f52-bluemix.cloudant.com/

if I replace the above url with a simple account like https://hardeys.cloudant.com, the post operator works. 

Can someone assist ?

**Comment by ddebrunner** [comment]
Do you see errors?

**Comment by hardeys** [comment]
Yes - below


"{"message":"Cloudant"}" 25 May 2016 16:02:48.449 [27716] DEBUG #splapptrc,J[16],P[908],o_DelivrRiderLevelRaceOutput.o_SinkCloundant M[Wire.java:org.apache.http.impl.conn.Wire.wire:63] - << "HTTP/1.0 400 Bad request[\r][\n]" 25 May 2016 16:02:48.451 [27716] DEBUG #splapptrc,J[16],P[908],o_DelivrRiderLevelRaceOutput.o_SinkCloundant M[Wire.java:org.apache.http.impl.conn.Wire.wire:63] - << "Cache-Control: no-cache[\r][\n]" 25 May 2016 16:02:48.452 [27716] DEBUG #splapptrc,J[16],P[908],o_DelivrRiderLevelRaceOutput.o_SinkCloundant M[Wire.java:org.apache.http.impl.conn.Wire.wire:63] - << "Connection: close[\r][\n]" 25 May 2016 16:02:48.452 [27716] DEBUG #splapptrc,J[16],P[908],o_DelivrRiderLevelRaceOutput.o_SinkCloundant M[Wire.java:org.apache.http.impl.conn.Wire.wire:63] - << "Content-Type: text/html[\r][\n]" 25 May 2016 16:02:48.452 [27716] DEBUG #splapptrc,J[16],P[908],o_DelivrRiderLevelRaceOutput.o_SinkCloundant M[Wire.java:org.apache.http.impl.conn.Wire.wire:63] - << "[\r][\n]"

**Comment by ddebrunner** [comment]
I doubt the length of the hostname has anything to do with it.

Is Streams running in Bluemix? Has the Cloudant service been bound to the Streams service?

**Comment by hardeys** [comment]
No. Streams is running on -prem.  I could write to bluemix cloudant service using curl from my server running streams.

I think it might be either length or characters in hostname or characters in hostname. I don't see any other reason. I can provide the full service credentials if you want to reproduce the scenario.

**Comment by hardeys** [comment]
@ddebrunner - were you able to replicate the problem ? any solution ?

**Comment by joergboe** [comment]
This operator is deprecated
