### ISSUE TITLE
Shall we open a new branch for toolkit globalization

### ISSUE THREAD

**Issue by joergboe** [IBMStreams/streamsx.inet#225]
Starting from branchv2.0.0 we plan to implement localization support for the internet toolkit.

Shall we open a new branch for this work?
Proposal:
- use new branch v2.0.1 branched from v2.0.0
- new branch is targeted for FP for Streams 4.2.1
- bump version number from 2.0.2 to 2.1.0
- branch v2.0.0 can still be used as FP for 4.0.x 4.1.x and 4.2.0

**Comment by joergboe** [comment]
New branch should have name v2.1.0

**Comment by ddebrunner** [comment]
Is there a typo with the version being 2.1.0 but the branch v.2.0.1 ?

**Comment by chanskw** [comment]
I believe the name of the new branch should be v2.1.x.

v2.0.0 Branch - is the maintenance branch in which no code changes and features should be checked in without committer vote and approvals.

v2.1.x Branch - Based from v2.0.0 branch should be used as branch for globalization work.

master - latest development branch. Keep in mind that whatever we do with v2.1.x brach need to be forward ported to the mater branch.

**Comment by joergboe** [comment]
I found in the history of the info.xml that the toolkit was in the past already at version 2.1.0__dev__.
But I do not think that this status was ever delivered.
Nevertheless I would propose to use for the localization task:
-bump version to 2.1.0
-create new branch v2.1.x based on v2.0.0

**Comment by chanskw** [comment]
Can you show me what you mean when you say we already bumped to version v2.1?  I just want to make sure that I did not miss anything here.  Thanks!

**Comment by joergboe** [comment]
see:
FTP Operators in inet toolkit #82
7c5cf26698a103f33184a01a9fbec89b25155836
Commits on Dec 19, 2014

**Comment by joergboe** [comment]
I created the v2.1.x branch and started work.
