### ISSUE TITLE
Globalizing the toolkit

### ISSUE THREAD

**Issue by gertmark** [IBMStreams/streamsx.inet#226]
Provide log messages for different locales via unique message ids: German (de_DE), French (fr_FR), Italian (it_IT), Spanish (es_ES). Brazilian Portuguese (pt_BR), Japanese (ja_JP), Simplified Chinese (zh_CN), Russian (ru_RU), Traditional Chinese (zh_TW), Korean (ko_KR). 
#225

**Comment by joergboe** [comment]
I created the v2.1.x branch and started work.

**Comment by ddebrunner** [comment]
@joergboe What are the plans to merge the globalization work to master?

**Comment by joergboe** [comment]
Task completed in branc v2.1.y, 2.1.x and master
