### ISSUE TITLE
Create release for 2.8.1

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/streamsx.inet#228]
Could we please create a new release, especially to make the enhancement from issue #223 available?

**Comment by ddebrunner** [comment]
Not sure we need to bump the version to 2.8, but I'd like to understand plans for merging globalization changes to master, see comment in #226.

**Comment by joergboe** [comment]
I'm going to merge the globalization changes into master branch right now.
If you want to have a release without the globalization, you should make a release now.
If you want to include globalization, you should wait for a few more days.
The version number is currently at 2.8.1

**Comment by ddebrunner** [comment]
So the version was correctly bumped to 2.8 because of new FTP functions.

**Comment by joergboe** [comment]
We should make a release now. Agreed?
