### ISSUE TITLE
Operators in branch v2.1.x should have the same code as in main branch

### ISSUE THREAD

**Issue by joergboe** [IBMStreams/streamsx.inet#237]
The operators InetSource, HTTPGetStream and HTTPPost should use the same code in master branch and in branch v2.1.x (which is released). I think the code has diverged for a long time. Should be corrected.

**Comment by joergboe** [comment]
I think we should merge for operators InetSource, HTTPGetStream and HTTPPost the code from master into v2.1.x

**Comment by ddebrunner** [comment]
I would guess most of the changes were for new functionality which should not go into a 2.1 branch, as it would require bumping to 2.1.

**Comment by joergboe** [comment]
Most of the changes for the functionality are in the new Operators HTTPJSONInjection, HTTPTuplexxx, HTTPXMLxxx...
The operators which are released in the product are InetSource, HTTPGetStream and HTTPPost. These operators have only a few functional changes in the master branch compared with the branch v2.1.x.
But there are a lot of code lines different between these branches. I think the code has diverged. I think it is worse to pull in the few function changes from master for these 3 operators and maintain only one common code in both branches for this 3 operators.

**Comment by gertmark** [comment]
You could do it in two steps: first merge InetSource, HTTPGetStream and HTTPPost. If that includes new functionality (e.g. new parameters) then bump the version. I consider that important for two reasons: 1) from user's perspective, because the current situation with different behavior is confusing, 2) for maintenance and testing, to have a unified code base again.
In a second step, you may add new operators but this is rather mid-term and should be treated as a separate issue.

**Comment by joergboe** [comment]
The version number was already bumped from 2.0.2 to 2.1.0
The master branch is currently at 2.8.1

**Comment by chanskw** [comment]
Please do not merge new code into v2.1 branch. This is a maintenance and is needed for building fix pack for the product. It you want the product to pick up new operators, we should clean up master and switch the product build to use master.

**Comment by joergboe** [comment]
I don't want to bring new operators into the product with this issue.
I want, that the code for the operators which are released with the product, is at the same level as the operators in the main branch are.
This should simplify the maintenance.
The code of the operators InetSource, HTTPStreamReader and HTTPPostOper has diverged over the time and I see no benefit when we release outdated code with the product.
The code in main branch has some enhancements compared to the code in V2.1.x:
InetSource:
 - New parameter: Iterations
HTTPStreamReader:
 - New param: ExtraHeader,
 - New param: AcceptAllCertificates,
HTTPPostOper:
 - NewParam: ConnectionTimeout,
 -New param: ExtraHeader,
 - New param: AcceptAllCertificates,
- New param: Include
The branch V2.1.x is a new branch for Tiber release. It was originally created for the translation work. But we can take the opportunity an fix diverged code too.

**Comment by ddebrunner** [comment]
I think it's ok to merge those changes in v2.1, but really I would prefer that the product move to later code with all the operators from the toolkit.

**Comment by BruceGlassford** [comment]
I'm with Dan on that - moving the shipped toolkit version to have all the operators and patches is important from a customer perspective.  Back patching 2.1 probably less so.  (Impetus to upgrade to newer /more powerful Streams versions anyways).
--------Bruce GlassfordIM Lab Services, US FederalIBM Software Group301-980-3326 (c)
 
 
----- Original message -----From: Dan Debrunner <notifications@github.com>To: "IBMStreams/streamsx.inet" <streamsx.inet@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: Re: [IBMStreams/streamsx.inet] Operators in branch v2.1.x should have the same code as in main branch (#237)Date: Fri, Dec 23, 2016 11:59 AM 
I think it's ok to merge those changes in v2.1, but really I would prefer that the product move to later code with all the operators from the toolkit.

**Comment by joergboe** [comment]
Branch 2.1.x is the dedicated release branch for 4.2.1 thus thus it the right branch to do this

**Comment by joergboe** [comment]
new branch 2.1.y has code base of master but is limited to InetSource and http operators
brach 2.1.x is obsolete
