### ISSUE TITLE
FTPWrapper error during PE startup

### ISSUE THREAD

**Issue by ulemanstreaming** [IBMStreams/streamsx.inet#244]
An application that uses HTTPGetJSONContent and httpGet(), but nothing to do with FTP, records the following error during startup:

```
FTPWrapper: Work with Curl version:libcurl/7.19.7 NSS/3.21 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
FTPWrapper: curl_version_info ssl_version=NSS/3.21 Basic ECC FTPWrapper: libssh_version=libssh2/1.4.2
FTPWrapper: Async DNS supported=0 06 Jan 2017 16:08:18.300 [9030] ERROR #splapptrc,J[0],P[0],Weather.FeaturesParser.OrientPolygons.RegionValidator,FTPWrapper M[FTPWrapper.cpp:Initializer:50] - There is already ssh lock call back function registered
```

Because the operator listed has nothing to do with anything in the inet toolkit, the assumption is that the exception happens during PE startup and gets assigned to the wrong operator (this error was observed in standalone mode and distributed with all operators fused).

Aside from logging this error there is no observable effect on the application.

**Comment by joergboe** [comment]
Which platform do you use? RHEL6?
This message is just a log.
But I wonder why there the FTPWrapper static initialization is execute if there is no FTP-Operator invoked.
There should not be any cpp code that includes or links the FTPWrapper module.
It seems that there is a link instruction issued for the FTPWrapper.

**Comment by joergboe** [comment]
And what is your Streams version?

**Comment by joergboe** [comment]
Correction was merged
