### ISSUE TITLE
samples/InetSource* applications fail to build.

### ISSUE THREAD

**Issue by siegenth** [IBMStreams/streamsx.inet#247]
Getting an error while attempting to build InetSource* samples, I'm not seeing an error in the other samples or in the tests. 

My development environment: 4.2 Quick Start Edition, this is my version info:

Version=4.2.0.0
ProductName=IBM Streams
Build=20160826145017
Architecture=x86_64
OS=Red Hat Enterprise Linux Server release 6.6 (Santiago)
OS.VERSION=6
OS.PATCH=6
Edition=Product
EditionName=IBM Streams

---- 
Here is the error I'm seeing....

`
[streamsadmin@streamsqse InetSource]$ make
/opt/ibm/InfoSphere_Streams/4.2.0.0/bin/sc -a -t ../../com.ibm.streamsx.inet:/opt/ibm/InfoSphere_Streams/4.2.0.0/toolkits/com.ibm.streamsx.inet -C -M com.ibm.streamsx.inet.sample::GetWeather
/opt/ibm/InfoSphere_Streams/4.2.0.0/bin/sc -a -t ../../com.ibm.streamsx.inet:/opt/ibm/InfoSphere_Streams/4.2.0.0/toolkits/com.ibm.streamsx.inet -M com.ibm.streamsx.inet.sample::GetWeather 
Checking the constraints.
Creating the types.
Creating the functions.
Creating the operators.
Creating the standalone application.
Creating the application model.
Building the binaries.
 [CXX-type] tuple<list<rstring> result>
 [CXX-operator] Result
src/operator/Result.cpp: In member function ‘virtual void SPL::_Operator::Result$OP::process(uint32_t)’:
src/operator/Result.cpp:824: error: no match for call to ‘(SPL::FormattableMessage0) (const char [1])’
make[1]: *** [build/operator/Result.o] Error 1
CDISP0141E ERROR: The compilation of the generated code failed.
make: *** [distributed] Error 1
[streamsadmin@streamsqse InetSource]$ 
`

Same error occurs with the other in InetSourceDynmicURL and InterSourceOutputAttributes.

**Comment by joergboe** [comment]
Yes that's true. I will check.
