### ISSUE TITLE
Change minimum Streams version to 4.0.1

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.inet#255]
For the master branch I'd like to move the minimum version to Streams 4.0.1 and hence Java 8.

Even though the v2 branches seem to have moved to 4.2 that cannot be done for master as there are multiple existing uses that have not yet moved to 4.2.

4.0.1 should be fine as:
 - 4.0.0 has some issues I think & 4.0.1 is recommended over that.
 - 4.0.0 uses Java 7 which is no longer recommended due to Java 8 security fixes.

**Comment by ddebrunner** [comment]
I propose this be done.

**Comment by chanskw** [comment]
+1

**Comment by joergboe** [comment]
The v2.1.y branche is targeted to 4.2. release. Thus the required product version is set to 4.2

**Comment by joergboe** [comment]
This issue is fixed with ee68c1e905214f0d61b23c44c10c0706fcc3f411
