### ISSUE TITLE
What's the difference between v2.1.x and v2.1.y?

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.inet#258]
What are the differences between these branches?

**Comment by ddebrunner** [comment]
Technically this shows (I think) the differences:

https://github.com/IBMStreams/streamsx.inet/compare/v2.1.x...v2.1.y

But I think you want a logical answer.

**Comment by chanskw** [comment]
I sort of found the answer here:
https://github.com/IBMStreams/streamsx.inet/wiki/Project-Branches

But I am unsure why we deprecated the v2.1.x stream and created a new one?  Why did we not merge the changes back to the v2.1.x stream?  And what does this really mean?

**Comment by joergboe** [comment]
The 2.1.y branch is branched from master branch and has deleted all the operators and function which are not released in the streams product.
The 2.1.x is a continuation of the v2.0.0 branch.
The internationalization is merged into master and v2.1.x and v2.1.y branch.
I wanted to make sure that the new v.2.1.y branch is a fork of the actual master branch code.

**Comment by chanskw** [comment]
Let me try to get this straight:
v2.0.0.x - This is for maintenance of Streams 4.0.x
v2.1.x - This is for maintenance for Streams 4.1 all the way up to Streams 4.2.0.x
v2.1.y - This is for maintenance for Streams 4.2.x and up? - including NL work.

Is this correct?

**Comment by joergboe** [comment]
v2.0.0.x - yes
v2.1.x - yes.  It has not been shipped.
v2.1.y - Is the maintenance stream for 4.2.1 - including NL
the maintenance stream for further streams product versions has to be decided

**Comment by chanskw** [comment]
Thanks!  I propose we delete the v2.1.x if it's not used anywhere.  I think this branch can cause confusion when we try to do maintenance.

**Comment by joergboe** [comment]
Yes we can delete the branch.
But my intention was to have it as a backup for the case if something went wrong with my fork from the master branch into the v2.1.y. 
But there are more branches which are not mentioned in the wiki. These branches seems to receive no commits since years. These are confusing too.
I propose these branches too

**Comment by joergboe** [comment]
Branch v2.1.x is deleted
