### ISSUE TITLE
Native Function hhpPut produces erroneous error logs

### ISSUE THREAD

**Issue by joergboe** [IBMStreams/streamsx.inet#268]
The httpPut function produces erroneous error logs like:

20 Apr 2017 08:36:47.770 [12245] ERROR #splapptrc,J[2],P[2],ObjStSink.ObjectStorageWrite,httpForStreams M[httpFunctions.cpp:readFromRstring:289]  - Size is 16372 blob size is 2000000000

if datablocks size is larger than the libcurl buffer.

The call back 'readFromRstring'
must not produce these error logs because this is a normal operation condition for large data blocks.

**Comment by markheger** [comment]
Awaiting this fix because it improves the performance since the trace does not appear anymore.
