### ISSUE TITLE
Use case for retrieving headers in httpGet function

### ISSUE THREAD

**Issue by swaqos** [IBMStreams/streamsx.inet#269]
I'm currently using this toolkit to create a sink operator that requires `httpGet` function to retrieve auth token from from an endpoint. However, the returned token and post endpoint are included in the header but not the response body. Unlike `httpPost` or `httpPut`, `httpGet` doesn't take in a `mutable list<rstring>` to save the headers, so I could not retrieve those information within Streams, and the endpoint does not accept POST requests. Is there any plan going forward updating `httpGet` for use case like this? or is there a reason `httpGet` was not designed to save the headers?

**Comment by joergboe** [comment]
It is implemented in PR #276

**Comment by joergboe** [comment]
Code merged
