### ISSUE TITLE
TLS 1.2 support

### ISSUE THREAD

**Issue by bmwilli** [IBMStreams/streamsx.inet#275]
Trying to figure out if this toolkit supports TLS 1.2 (Customer has mandated it). It looks like Jetty 8.1.3 (from Juno R2) is the version it compiles in, but could someone who builds this toolkit verify?  We have had trouble with Jetty 8.1.3 and another operator we wrote supporting TLS 1.2.   Any information / suggestions would be appreciated.

Brian

**Comment by joergboe** [comment]
This issue in now tracked here:
https://github.com/IBMStreams/streamsx.inetserver/issues/10
