### ISSUE TITLE
Setting HTTPPost acceptAllCertificates to true disables HTTP.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.inet#278]
With `HTTPPost` setting
```
param acceptAllCertificates:true;
```

disables the HTTP protocol. The operator will receive a  `org.apache.http.client.ClientProtocolException` which has a cause of:

`Caused by: org.apache.http.HttpException: Scheme 'http' not registered.`

Seems this should be handled better, making the cause more obvious. The docs should at least state that only use the param with HTTPS.

**Comment by joergboe** [comment]
This operator is deprecated. Use HTTPRequest
