### ISSUE TITLE
Fix metrics in HTTPTupleRequest

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.inet#287]
Several of the metrics are stored in static fields which is incorrect, as if multiple operators are fused into the same PE multiple operators will update the same metric in one of the operators.

Probably was done this way (static) to enabled access from unrelated code.

Probably best to wait until refactoring is complete ( #286 ) before fixing.

@siegenth

**Comment by joergboe** [comment]
Issue moved to:
https://github.com/IBMStreams/streamsx.inetserver/issues/3
