### ISSUE TITLE
Does HTTPTupleInject work on Bluemix?

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.inet#294]
Hi -

I am wondering if anyone has tried running HTTPTupleInject on Bluemix?  I have tried it with secured gateway.  While I can get HTTPTupleView to work, I can never work HTTPTupleInject to work.  The application was not able to receive the tuple.  

Anyone has experience with this?
Thanks!

**Comment by ddebrunner** [comment]
Did you try a GET instead of a POST?

**Comment by chanskw** [comment]
Yeah... GET works, but POST does not.  I am trying to debug it.
