### ISSUE TITLE
InetSource throws error on apparently working URL

### ISSUE THREAD

**Issue by mfeblowitz** [IBMStreams/streamsx.inet#297]
Encountered when using InetSource to access an RSS URL - the URL appears to be correct but:

InetSourceStream,InetSource M[InetSourceStream.cpp:checkURI:704]  - URL [https://www.justice.gov/feeds/justice-news.xml?type=All&component[646]=646](https://www.justice.gov/feeds/justice-news.xml?type=All&component[646]=646) is invalid, "The Uniform Resource Identifier string https://www.justice.gov/feeds/justice-news.xml?type=All&component[646]=646 specified in the URIList parameter contains a syntax error. The Processing Element will shut down now."

**Comment by ddebrunner** [comment]
did you try:
https://www.justice.gov/feeds/justice-news.xml?type=All&component%5B646%5D=646

**Comment by mfeblowitz** [comment]
Thanks - we’ll give it a try. Not sure whether our code URL-encodes. Also not sure whether InetSource is crashing the PE or our code is.

**Comment by ddebrunner** [comment]
Looks like the URI checker is rejecting the URL from this regex:
https://github.com/IBMStreams/streamsx.inet/blob/master/com.ibm.streamsx.inet/com.ibm.streamsx.inet/InetSource/URIHelperCpp.cgt#L40

**Comment by ddebrunner** [comment]
RFC2396 says use of `[`, `]` is _unwise_.

https://www.ietf.org/rfc/rfc2396.txt

**Comment by mfeblowitz** [comment]
Unwise, indeed.

**Comment by joergboe** [comment]
The InetSource operators terminates the PE if a statically applied uri fails to pass the uri check.
An invalid uri which is applied dynamically is ignored and logged, but does no PE termination.

**Comment by ddebrunner** [comment]
> Superseded anywhere, or just ignored
Not sure if "ignored" is correct, could it just be a browser is "correcting" the URI by encoding it, that's what chrome did for me.

**Comment by mfeblowitz** [comment]
So, we'll try url-encoding the rss feed url, to see whether that makes the difference. That could tell us that our code should probably take that on as the urls go into the source url file.
I'm wondering whether there could be a flag added to the operator, to choose whether bad urls should be ignored or whether the application should terminate.

**Comment by ejpring** [comment]
I'd be happy with an InsetSource operator parameter of type 'boolean', maybe named 'terminateOnInvalidURL', with a default value of 'true'.

**Comment by joergboe** [comment]
PR #304 addresses this issue
