### ISSUE TITLE
Create AsyncHttp Operator that could be used in the middle of a job or as a target

### ISSUE THREAD

**Issue by ilanprager** [IBMStreams/streamsx.inet#306]
In cases where ordering isn't a requirement, it would be helpful to fire off an HTTP request per arriving tuple and place the responses on the output stream whenever they arrive, without causing synchronous bottlenecks or having to spawn multiple threads.  
A potential implementation direction would be to use async IO such as in https://hc.apache.org/httpcomponents-asyncclient-4.1.x/index.html.
Every tuple would include information about the HTTP request (e.g. method, headers, body, etc.) along with a correlation key that would then appear in the output stream along with the response metadata and data.
There would still be some throttling limit set on number of concurrent requests, but this could be quite acceptable for certain use cases.
In addition, when used as a target, there could be a fire and forget flag that would enable the requests to be sent without incurring processing of the response.
The exact operator contract needs to be further defined, but eventually it might make sense to converge the implementation of the existing HTTP operators with this one.

**Comment by ddebrunner** [comment]
I think this would be an option of HTTPRequest (see pr #241) rather than a separate operator.

https://github.com/IBMStreams/streamsx.inet/wiki/HTTPRequest-operator

**Comment by joergboe** [comment]
These are some of the primary Streams processing principles: Parallelism and streamlining. We can achieve these goals also by putting the HTTP operator into a certain composite operator.
We can also use the async features of the client inside of the operator. As far as I understand the async clients operation the receive threas are spawned under the hood.

**Comment by joergboe** [comment]
I'm not saying that we should not do it

**Comment by ddebrunner** [comment]
I think we have to have both options (parallelism by Streams UDP) and async within the operator itself.

Since this is a connection to an external system there may be constraints that would be impossible to enforce with UDP, e.g. rate limiting for HTTP requests, contract requires only a single connection, etc.

**Comment by leongor** [comment]
Regarding HTTP client async implementation, I have a prototype of C++ primitive operator based on the native functions developed for our previous engagement.
It's built on top of [cpp-netlib library](http://cpp-netlib.org).
All the requests are async and responses are handled by callbacks.
[cpp-netlib library](http://cpp-netlib.org) is based on boost asio library that is known for its async nature and high performance. In fact, the library is a core component of [streamsx.tcp toolkit](https://github.com/IBMStreams/streamsx.tcp).
@joergboe @ddebrunner Do you think it can be valuable addition to Inet toolkit?

**Comment by mikespicer** [comment]
Should this be a new http async operator or a parameter on the http-request operator as @ddebrunner suggested above.

**Comment by Yifat-Yulevich** [comment]
Should we use the cpp operator we will have to take the separate operator approach as the original operator is in java.

**Comment by Yifat-Yulevich** [comment]
Following is HTTPRequestAsync operator spec wiki:
https://github.com/IBMStreams/streamsx.inet/wiki/HTTPRequestAsync-operator

**Comment by joergboe** [comment]
Question relating the operator design:
Is there really the requirement to change the http-method on the fly?
I wonder that the expression-mode for the method-parameter is 'Expression' but the expression-mode for the contentType-parameter is 'CustomLiteral' which is compile time constant.

**Comment by leongor** [comment]
As discussed [here](https://github.com/IBMStreams/streamsx.inet/pull/310), HTTPRequestAsync will be placed in a separate toolkit in [streamsx.inet](https://github.com/IBMStreams/streamsx.inet) repository.
We should decide about the toolkit's name and the operator's namespace. The current suggestion:
toolkit: com.ibm.streamsx.inet.async
namespace: com.ibm.streamsx.inet.http

**Comment by leongor** [comment]
As there are no other suggestions, I'm going to open a new PR using those names.

**Comment by ddebrunner** [comment]
How would this differ from the operator in PR #316?

**Comment by leongor** [comment]
@ddebrunner The operators are fundamentally different.

HTTPParallelRequest from PR #316 is an SPL composite wrapping HTTP synchronous functions with parallel annotation. That means once all HTTP requests are sent the threads will be blocked waiting for HTTP responses.

HTTPRequestAsync is a primitive operator built on top of [cpp-netlib](http://cpp-netlib.org/) asynchronous library. That means once HTTP request is sent the operator thread is immediately released for the next tuple (no network latency), then each HTTP response is handled by a callback.

**Comment by ddebrunner** [comment]
How would an application developer decided to use one or the other?

**Comment by leongor** [comment]
It depends on functional requirements.

If SPL applications needs to send HTTP requests to many servers, possibly with a bad response time, with a high rate then HTTPRequestAsync is a better choice.

If SPL applications needs to send HTTP requests to few servers with a good response time and a rate is less important then HTTPParallelRequest fits well.
