### ISSUE TITLE
HTTPTupleInjection documentation

### ISSUE THREAD

**Issue by BrianMWest** [IBMStreams/streamsx.inet#312]
It should specify in the documentation some of the compile time context checks, such as certificateAlias being required if keyStore and keyStorePassword are set. I didn't see that in the docs.

**Comment by ddebrunner** [comment]
It's somewhat covered here:
http://ibmstreams.github.io/streamsx.inet/com.ibm.streamsx.inet/doc/spldoc/html/tk$com.ibm.streamsx.inet/ns$com.ibm.streamsx.inet.rest$1.html

**Comment by joergboe** [comment]
The operator has been moved to streamsx.inetserver toolkit.
