### ISSUE TITLE
Broken link in spl doc on github pages

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/streamsx.inet#313]
From the [toolkit web page](http://ibmstreams.github.io/streamsx.inet/), click SPL Doc, and click the namespace `com.ibm.streamsx.inet.ftp`
The page does not open. The link for that namespace is broken.

**Comment by joergboe** [comment]
Is a typo in info.xml. I will fix it

**Comment by joergboe** [comment]
PR is there
