### ISSUE TITLE
HTTPRequestAsync - gcc 4.7

### ISSUE THREAD

**Issue by AlexDag** [IBMStreams/streamsx.inet#325]

**Comment by leongor** [comment]
Hi Alex,

You need to download Developer Toolset.
For Centos 6: 
`sudo yum install centos-release-scl -y`

For RH6:
`sudo yum-config-manager --enable rhel-server-rhscl-7-rpms`

Then install it with other prerequisites:
`sudo yum install cmake devtoolset-4-gcc-c++ openssl-devel unzip wget -y`

Then run the ant build from the toolkit root directory:
`scl enable devtoolset-4 ant`

**Comment by AlexDag** [comment]
thanks, it'd run well.
