### ISSUE TITLE
HTTPRequestAsync - POST method with "system: Connection refused"

### ISSUE THREAD

**Issue by AlexDag** [IBMStreams/streamsx.inet#326]
We try to use HTTPRequestAsync from streamsx.inet/sample/HTTPClientAsync.
We change method to POST and try to connect HTTPClientAsync to very simple REST dummy and we see the message "system: Connection refused" on Streams IDE console.
What does it mean ? 
Are there the additional configurations for HTTPClientAsync ?

The content of our  HTTPClientAsync.spl is the same as streamsx.inet/samples/HTTPClientAsync/com.ibm.streamsx.inet.http.sample/HTTPClientAsync.spl , except param : ur  &  method.

**Comment by leongor** [comment]
The error `system: Connection refused` means TCP connection couldn't be established. Which url are you trying to call?

**Comment by AlexDag** [comment]
it's url our spring-boot jar web server that run on the same PC, Postman client(www.getpostman.com) run well on this url, browser GET run well too. As I can think it's message from cpp-netlib-archive , no ?

**Comment by leongor** [comment]
`cpp-netlib` is based `boost.asio` which gives this error code.
Which port are you connecting?

**Comment by AlexDag** [comment]
recently , I've tried that from HTTPClientAsync.spl  > http://httpbin.org/post
Streams console message>
 `http://httpbin.org/post
  asio.netdb: Host not found (non-authoritative), try again later
  2`

**Comment by AlexDag** [comment]
URL  must have "http://" , message "system: Connection refused" was the case of the URL without this prefix. Issue closed, thanks for your fast attention..

**Comment by leongor** [comment]
Right, because choosing http or https in url is important regarding security.
