### ISSUE TITLE
HTTPRequest should allow passing of accessToken as a stream attribute

### ISSUE THREAD

**Issue by nmwaara** [IBMStreams/streamsx.inet#334]
This enhancement is based off a customer request. Currently, the HTTPRequest operator does not have a way to pass an accessToken for OAUTH2 authentication via a stream attribute (instead, only valid using the SPL operator parameters, which are only evaluated at program startup time). 

Adding this implementation would allow for a token that is changing over time to be updated as necessary and passed along as a stream attribute, rather than just evaluated at program startup time.

**Comment by joergboe** [comment]
v3.0.0 will contain the changes
