### ISSUE TITLE
HTTPRequest is not returning a response.

### ISSUE THREAD

**Issue by GilbertLS** [IBMStreams/streamsx.inet#348]
I'm getting back
`{data="", errorMessage="", responseCode="0", dataSize="0"}`
I know that the post request is going through, because I see the data in my cloudant instance.

Here is the relevant code.
```
(stream<HTTPResponse> CloudantResponse) = HTTPRequest(CloudantPayload as CP)
{
	param
		fixedMethod: POST ;
		fixedContentType: "application/json" ;
		requestBodyAttribute : jsonString ;
		sslAcceptAllCertificates : true ;
		authenticationType : "STANDARD" ;
		authenticationProperties : "ANY_HOST=" + $CLOUDANT_USER_ID + ":" +
			$CLOUDANT_PASSWORD ;
		url : url ;
}

() as Printer = Custom(CloudantResponse as CR)
{
	logic
		onTuple CR :
		{
			println(CR);
		}
	}
```

**Comment by joergboe** [comment]
For the HTTPRequest operator you must define the output assignements. All operator parameters starting with 'output..' must be used. For the error message the parameter 
In your case you must add the following parameters to the operator invocation:

             outputStatusCode: "responseCode";

If you want to output the whole reponse line use parameter `outputStatus`.

The assignement of the response body (data) depends on the returned data type. In many caseas
 a paramter:
     
       outputBody: "data";

should work.
There is no explicit data size return function but the size of the data should be sufficient in most of the cases. Alternatively you inspect the response headers with parameter `outputHeader` (the type of this atribute must be listyrstring>)

With parameter `errorDiagnostics` you may specify a output attribute that delivers diagnostics information e.g.: when the program execution of the http operation throws an exception.

see also here : https://ibmstreams.github.io/streamsx.inet/doc/spldoc/html/

**Comment by GilbertLS** [comment]
Ah thanks, I missed the output attributes.
