### ISSUE TITLE
Add live table support for HTTPTupleView using a Dojo grid.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.inet#48]
Using the meta-data from HTTPTupleView, add a html page that automatically provides links to a live table (automatically updated) view of any stream exposed by HTTPTupleView.

Would use the Dojo Javascript libraries from $STREAMS_INSTALL/ext/dojo

Basically allows anyone using HTTPTupleView to have instant live views of their feeds, rather than just a JSON static view. There's no requirement for any application to use Dojo, this is just an out of the box, easy to use, getting started feature.

**Comment by ddebrunner** [comment]
This is partially implemented, using the relative URL
streamsx.inet.resources/dojo/viewall.html
provides auto visualization of all input ports HTTPTupleView operators.

More work is needed to refine the live table views, e.g. the default number of rows show is not useful and scrolling gets reset by new data.

**Comment by joergboe** [comment]
This issue is now tracked here:
https://github.com/IBMStreams/streamsx.inetserver/issues/8
