### ISSUE TITLE
InetSource sample does not compile

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.inet#65]
1.  download release from here:
   https://github.com/IBMStreams/streamsx.inet/releases
2.  extract the release
3.  import InetSource sample as example
4.  Add streamsx.inet toolkit as toolkit location in studio

The sample does not compile:
make

/homes/chanskw/streams//bin/sc -a -t ../../com.ibm.streamsx.inet -T -M com.ibm.streamsx.inet.sample::GetWeather 
CDISP0727W WARNING: The ../../com.ibm.streamsx.inet input path is not a directory.
CDISP0385E ERROR: The InetSourceSample toolkit requires version 1.0.0 of the com.ibm.streamsx.inet toolkit, but version 1.0.0 of the com.ibm.streamsx.inet toolkit is not available.
CDISP0131E ERROR: Errors occurred while the toolkits were loading.
make: **\* [standalone] Error 1

---- External builder for project InetSource completed in 1.692 seconds ----

**Comment by chanskw** [comment]
I suggest we do this:
1)  Makefile - focus on getting this to work for command line user.
2)  set up build configuration and the toolkit project... and use internal studio builder to build.  Make sure the internal build can build correctly, and use toolkit locations from Streams Studio to build

What we get is this:
- command line user will be able to use Makefile to build
- studio user uses internal builder to build.  Do not set up the project to use external builder for studio project.

**Comment by joergboe** [comment]
see PR #340
