### ISSUE TITLE
inet toolkit at github should not bundle junit test cases and junit lib dependency

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.inet#68]
inet toolkit at github includes junit test cases and junit lib dependency, which should be removed.

Also the current junit dependency results in compile error as the junit test cases requires version 4 to work, but it currently specifies version 3.

**Comment by ddebrunner** [comment]
Shouldn't toolkits include test cases, and JUnit is a valid testing approach, so I'm not sure what needs to be removed. Is it that the test cases are ending up in the release bundle?

**Comment by chanskw** [comment]
I cannot remember exactly anymore.  When I looked at it I think the Junit testcases were part of the toolkit itself, and not separated.  So, the suggestion was to separate out the tests from the toolkit, so that the toolkit bundle does not have to have junit dependencies.

**Comment by joergboe** [comment]
The junit testcases are not compiled during regular build run, so there is no general dependency to junit.
