### ISSUE TITLE
HTTPXMLInjection operator in inet tookkit does not have a form for submitting xml data.

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.inet#69]
In the inet toolkit, the HTTPTupleInjection operator provides a form at prefix/ports/output/port index/form for submitting tuples to the operator, however the HTTPXMLInjection operator does not provide a form similar to HTTPTupleInjection for the same purpose.

**Comment by ddebrunner** [comment]
A better approach for testing might be to use a browser extension that supports POST requests, I used "Postman - REST Client" to test the HTTPJSONInjection operator.

The FORM provided by HTTPTupleInjection is natural for humans, I'm not sure a form expecting XML or JSON would be easy for people to use.

I'm also assuming this is mainly for testing or quick demos, any real application is likely to have HTML defining their own form

**Comment by joergboe** [comment]
This issue is now tracked here:
https://github.com/IBMStreams/streamsx.inetserver/issues/9
