### ISSUE TITLE
Add ftp operators

### ISSUE THREAD

**Issue by joergboe** [IBMStreams/streamsx.inet#74]
We plan to contribute 3 primitive operators to inet toolkit. These operators are streams source and 
sink operators to reade / write directly to/from an ftp server:

FTPReader - This source operator is able to scan a director at a remote host or a may receive files from a remote host via FTP, FTPS or SFTP protocol.

FTPPutFile - Put File operator is able to put a local file to a remote host via FTP, FTPS or SFTP protocol.

FTPCommand - This command operator is able to execute a ftp command at remote host via FTP, FTPS or SFTP protocol.

What should be the namespace for the operators ?
com.ibm.streamsx.inet.ftp 

Or sshould it be a different namespace?

**Comment by hildrum** [comment]
These were pulled in [pull request 82](https://github.com/IBMStreams/streamsx.inet/pull/82) so closing.
