### ISSUE TITLE
SPLDoc issue in HTTPTupleView

### ISSUE THREAD

**Issue by hildrum** [IBMStreams/streamsx.inet#81]
Is this still true:

The documentation says <a href="https://github.com/IBMStreams/streamsx.inet/blob/master/com.ibm.streamsx.inet/impl/java/src/com/ibm/streamsx/inet/rest/ops/TupleView.java#L63">The default URL for the web-server resolves to `{data_dir}/html/index.html`.</a>, but in  ServerEngine.java <a href="https://github.com/IBMStreams/streamsx.inet/blob/master/com.ibm.streamsx.inet/impl/java/src/com/ibm/streamsx/inet/rest/engine/ServletEngine.java#L271">`PathConversionHelper.convertToAbsPath(baseResourceURI, "opt/html")`</a>

**Comment by joergboe** [comment]
The doc issue is resolved
