### ISSUE TITLE
Support consistent regions

### ISSUE THREAD

**Issue by rohitsw** [IBMStreams/streamsx.inet#83]
https://github.com/IBMStreams/streamsx.inet/wiki/Proposed-Consistent-Cut-Changes

**Comment by chanskw** [comment]
For the source operators that we do not allow in a consistent region, is there any buffer in the operator before the tuples are sent out?

For these cases, users are expected to use the ReplayableStart operator downstream from the source operator.  The ReplayableStart operator can buffer and replay tuples in case of application failure.  However, if your source operator has buffer, we can still lose tuples from the buffer if the source operator crashes.  

We have similar problems with the MQTTSource operator.  The MQTTSource operator cannot be placed in a consistent region as we cannot control message acknoledgement.  However, the operator itself has a buffer before tuples are sent out.  The plan for us is to provide a parameter to control the buffer size.  This allows user to reduce the risk of losing messages in case the operator crashes.

Just want to share this with you and see you have similar issues.

**Comment by rohitsw** [comment]
The HTTPGetStream and HTTPPost operators do not contain any internal buffers. Data is sent out as soon as it is received.
