### ISSUE TITLE
Fix the __dev__, commit hash, and version handling.

### ISSUE THREAD

**Issue by hildrum** [IBMStreams/streamsx.inet#90]
Idea:
- When toolkit is build, the commit hash is placed in the version so we can identify which toolkit was built.
- For release versions, we should not include either **dev** or a commit hash.

**Comment by ddebrunner** [comment]
Has the __dev__ scheme been changed? The version in info.xml is now at 2.5.0 without the __dev__ tag, but the top-level build.xml still includes modifying __dev__.

**Comment by hildrum** [comment]
Before the release, @chanskw was unhappy with the commit hash being in the release.  I took the \_\_dev\_\_ out of the info.xml and opened this item to remind me to do a real fix when when the pressure was off.

**Comment by joergboe** [comment]
A release should never be produced from a __dev__ version. Insert the correct version string in info.xml in a release version.
