### ISSUE TITLE
FTP issue with "SITE" command

### ISSUE THREAD

**Issue by ghost** [IBMStreams/streamsx.inet#96]
We're are trying to ftp a "FIFO" file from a client server into InfoSphere Streams server. We used the operator "InetSource" but not successful with the following commands:
   site UNIXFILETYPE=FIFO
   site FIFOIOTIME=120
   site FIFOOPENTIME=240

Could you please add this subcommand "site" to the existing operator so we would be able to 
receive the FIFO?

Thank you very much and please contact me if you have any further questions.
Thuy Nguyen - nthuy@us.ibm.com

**Comment by hildrum** [comment]
I'm afraid I don't understand this request.  The InetSource operator doesn't support any commands of that type; it just gets URLs.  What was the SPL code you tried to run?

**Comment by nthuy** [comment]
Hi there,
I did not mean to change InetSource Operator. 
We would like to include that "SITE" command for FTP in any Streams's operators so we would be able to receive the FIFO file.

Thank you for looking into this.

**Comment by hildrum** [comment]
This repository is for discussion of this particular toolkit.  For general Streams how-to questions, you should go to the [StreamsDev Forum](https://developer.ibm.com/answers/smart-spaces/22/streamsdev.html).

**Comment by hildrum** [comment]
After some discussion, I think I understand a little better.  @joergboe is this something that the FTPReader operator could be modified to handle?

**Comment by joergboe** [comment]
Use streamsx.shell toolkit for fifos
