### ISSUE TITLE
Error while compiling the sample

### ISSUE THREAD

**Issue by anitajebaraj** [IBMStreams/streamsx.inet#97]
when I try to compile the samples in streams studio, I keep getting the following errors and warnings and not able to do anything further,

CDISP0543W WARNING: The
bin/com.ibm.streamsx.inet.ftp.sample/.namespace file is not indexed
because it is in a reserved directory.
CDISP0543W WARNING: The
bin/com.ibm.streamsx.inet.ftp.sample/PutFile.spl file is not indexed
because it is in a reserved directory.
CDISP0727W WARNING: The ../../com.ibm.streamsx.inet input path is not
a directory.
CDISP0385E ERROR: The FTP PutFile sample toolkit requires version
[2.0.0,3.0.0) of the com.ibm.streamsx.inet toolkit, but version
[2.0.0,3.0.0) of the com.ibm.streamsx.inet toolkit is not available.
CDISP0131E ERROR: Errors occurred while the toolkits were loading.
make: **\* [standalone] Error 1

**Comment by hildrum** [comment]
I've seen those warnings before; they aren't a problem.  

The ERROR is what's stopping you; it looks like you didn't add com.ibm.streamsx.inet to your list of toolkits in StreamsExplorer.  
![streamsexplorer](https://cloud.githubusercontent.com/assets/5419652/6062575/dc5b3586-ad1e-11e4-9f0e-b1c8ac58870b.jpg)
