### ISSUE TITLE
Build and dependency clean up for Inet toolkit

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.inet#99]
We need to clean up the build script and dependency set up for the toolkit.
We have to very different approaches:
- For some operators, we have downloaded the required jar files and checked in the dependencies as part of the project
- For other operators, we rely on maven to fetch dependencies.

We end up getting dependencies with conflicting versions in the toolkit... and makes it difficult to create release build that works.

**Comment by joergboe** [comment]
Now everything comes from downloaded jars
